/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  KEEP_VIEW_TYPE: () => KEEP_VIEW_TYPE,
  KeepView: () => KeepView,
  default: () => KeepPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var KEEP_VIEW_TYPE = "keep-view";
var DEFAULT_TAG_FILTER = "#WIP";
var RANDOM_FILE_COUNT = 15;
var RENDER_INITIAL_LIMIT = 100;
var RENDER_MORE_STEP = 100;
var SEARCH_CONTENT_BATCH = 40;
var RENDER_YIELD_EVERY = 20;
var DEFAULT_SCRATCH_FOLDER = "__masonry-scratch";
var DEFAULT_SETTINGS = {
  canvasLabelSplitEnabled: true,
  scratchFolder: DEFAULT_SCRATCH_FOLDER,
  newFileFolder: ""
};
function normalizeScratchFolder(raw) {
  const cleaned = (raw != null ? raw : "").replace(/\\/g, "/").trim().replace(/^\/+|\/+$/g, "").replace(/\/{2,}/g, "/");
  return cleaned || DEFAULT_SCRATCH_FOLDER;
}
function normalizeNewFileFolder(raw) {
  return (raw != null ? raw : "").replace(/\\/g, "/").trim().replace(/^\/+|\/+$/g, "").replace(/\/{2,}/g, "/");
}
var NoteEditModal = class {
  constructor(app, file, keepLeaf, onCloseCallback, selectedFolder = "", selectedTag = "", hideTitle = false) {
    this.editorLeaf = null;
    this.prevActiveEditor = null;
    this.hasSavedActiveEditor = false;
    this.pushedModalScope = false;
    this.isOpen = false;
    this.origSetActiveLeaf = null;
    this.origGetActiveViewOfType = null;
    this.origGetActiveFile = null;
    this.onModalFocusIn = () => {
      this.claimActiveEditor();
    };
    this.app = app;
    this.file = file;
    this.keepLeaf = keepLeaf;
    this.onCloseCallback = onCloseCallback;
    this.selectedFolder = selectedFolder;
    this.selectedTag = selectedTag;
    this.hideTitle = hideTitle;
    this.scope = new import_obsidian.Scope(this.app.scope);
    this.scope.register(null, "Escape", () => {
      this.close();
      return false;
    });
    this.containerEl = document.createElement("div");
    this.containerEl.addClass("modal-container", "mod-dim");
    this.bgEl = this.containerEl.createDiv({ cls: "modal-bg keep-modal-bg" });
    this.bgEl.addEventListener("click", () => this.close());
    this.modalEl = this.containerEl.createDiv({ cls: "modal keep-editor-modal" });
    if (this.hideTitle)
      this.modalEl.addClass("keep-hide-title");
    this.contentEl = this.modalEl.createDiv({ cls: "modal-content keep-editor-modal-content" });
  }
  open() {
    if (this.isOpen)
      return;
    this.isOpen = true;
    document.body.appendChild(this.containerEl);
    this.app.keymap.pushScope(this.scope);
    this.pushedModalScope = true;
    void this.onOpen();
  }
  getEditorView() {
    var _a;
    const view = (_a = this.editorLeaf) == null ? void 0 : _a.view;
    return view != null ? view : null;
  }
  isEditorFocused() {
    const ae = document.activeElement;
    return !!ae && !!this.contentEl && this.contentEl.contains(ae);
  }
  /** デタッチleaf内のviewを activeEditor として振る舞わせる。view.scopeはpushしない(Escを横取りしてモーダルが閉じなくなるため)。ホットキーはmodal scope→app.scopeへのフォールスルーで届く。 */
  claimActiveEditor() {
    const view = this.getEditorView();
    if (!view)
      return;
    if (!this.hasSavedActiveEditor) {
      this.prevActiveEditor = this.app.workspace.activeEditor;
      this.hasSavedActiveEditor = true;
    }
    if (this.app.workspace.activeEditor !== view) {
      this.app.workspace.activeEditor = view;
    }
  }
  releaseActiveEditor() {
    const view = this.getEditorView();
    if (this.hasSavedActiveEditor) {
      if (!view || this.app.workspace.activeEditor === view) {
        this.app.workspace.activeEditor = this.prevActiveEditor;
      }
      this.prevActiveEditor = null;
      this.hasSavedActiveEditor = false;
    }
  }
  /**
   * Obsidianコアは activeEditor が MarkdownView 外にあるとクリアしたり、
   * getActiveViewOfType/getActiveFile が背後のleafを返すため、
   * モーダル表示中だけworkspaceの該当箇所をモーダル内に向ける。
   * 閉じる際に必ず元に戻す。
   */
  patchWorkspace() {
    const ws = this.app.workspace;
    if (!this.origSetActiveLeaf) {
      const orig = ws.setActiveLeaf.bind(ws);
      this.origSetActiveLeaf = orig;
      const self = this;
      ws.setActiveLeaf = function(leaf, ...args) {
        if (self.isOpen && self.isEditorFocused())
          return;
        return orig.apply(ws, [leaf, ...args]);
      };
    }
    if (!this.origGetActiveViewOfType) {
      const orig = ws.getActiveViewOfType.bind(ws);
      this.origGetActiveViewOfType = orig;
      const self = this;
      ws.getActiveViewOfType = function(type) {
        var _a;
        const v = (_a = self.editorLeaf) == null ? void 0 : _a.view;
        try {
          if (self.isOpen && v && v instanceof type)
            return v;
        } catch (e) {
        }
        return orig.apply(ws, [type]);
      };
    }
    if (!this.origGetActiveFile) {
      const orig = ws.getActiveFile.bind(ws);
      this.origGetActiveFile = orig;
      const self = this;
      ws.getActiveFile = function() {
        if (self.isOpen && self.file)
          return self.file;
        return orig.apply(ws);
      };
    }
  }
  unpatchWorkspace() {
    const ws = this.app.workspace;
    if (this.origSetActiveLeaf) {
      ws.setActiveLeaf = this.origSetActiveLeaf;
      this.origSetActiveLeaf = null;
    }
    if (this.origGetActiveViewOfType) {
      ws.getActiveViewOfType = this.origGetActiveViewOfType;
      this.origGetActiveViewOfType = null;
    }
    if (this.origGetActiveFile) {
      ws.getActiveFile = this.origGetActiveFile;
      this.origGetActiveFile = null;
    }
  }
  async onOpen() {
    this.contentEl.empty();
    let isNewFile = false;
    if (!this.file) {
      const basePath = this.selectedFolder ? `${this.selectedFolder}/` : "";
      if (this.selectedFolder) {
        const existing = this.app.vault.getAbstractFileByPath(this.selectedFolder);
        if (!existing) {
          await this.app.vault.createFolder(this.selectedFolder);
        }
      }
      let newPath = `${basePath}Untitled.md`;
      let counter = 1;
      while (this.app.vault.getAbstractFileByPath(newPath)) {
        newPath = `${basePath}Untitled ${counter}.md`;
        counter++;
      }
      this.file = await this.app.vault.create(newPath, "");
      if (this.selectedTag) {
        await this.app.fileManager.processFrontMatter(this.file, (fm) => {
          if (!fm.tags) {
            fm.tags = [];
          } else if (typeof fm.tags === "string") {
            fm.tags = [fm.tags];
          }
          const cleanTag = this.selectedTag.replace(/^#/, "");
          if (!fm.tags.includes(cleanTag)) {
            fm.tags.push(cleanTag);
          }
        });
      }
      isNewFile = true;
    }
    const LeafConstructor = this.keepLeaf.constructor;
    this.editorLeaf = new LeafConstructor(this.app);
    const leafEl = this.editorLeaf.containerEl;
    this.contentEl.appendChild(leafEl);
    if (this.editorLeaf && this.file) {
      const leaf = this.editorLeaf;
      await leaf.openFile(this.file);
      if (!this.isOpen || this.editorLeaf !== leaf) {
        leaf.detach();
        return;
      }
      this.patchWorkspace();
      this.contentEl.addEventListener("focusin", this.onModalFocusIn);
      this.claimActiveEditor();
      if (isNewFile) {
        setTimeout(() => {
          const inlineTitle = this.contentEl.querySelector(".inline-title");
          if (inlineTitle) {
            inlineTitle.focus();
            const range = document.createRange();
            range.selectNodeContents(inlineTitle);
            const sel = window.getSelection();
            if (sel) {
              sel.removeAllRanges();
              sel.addRange(range);
            }
          } else {
            const headerTitle = this.contentEl.querySelector(".view-header-title");
            if (headerTitle) {
              headerTitle.click();
            }
          }
        }, 150);
      }
    }
  }
  close() {
    if (!this.isOpen)
      return;
    this.isOpen = false;
    this.contentEl.removeEventListener("focusin", this.onModalFocusIn);
    this.releaseActiveEditor();
    this.unpatchWorkspace();
    if (this.pushedModalScope) {
      try {
        this.app.keymap.popScope(this.scope);
      } catch (e) {
      }
      this.pushedModalScope = false;
    }
    if (this.editorLeaf) {
      this.editorLeaf.detach();
      this.editorLeaf = null;
    }
    this.containerEl.remove();
    this.contentEl.empty();
    this.app.workspace.setActiveLeaf(this.keepLeaf, { focus: true });
    this.onCloseCallback();
  }
};
var _KeepView = class extends import_obsidian.ItemView {
  constructor(leaf) {
    super(leaf);
    this.filterContainer = null;
    this.leftFilters = null;
    this.createButton = null;
    this.canvasBanner = null;
    this.isRendering = false;
    this.pendingRender = false;
    this.renderTimeout = null;
    this.hasAppliedDefaultTagFilter = false;
    this.canvasFocusCycle = {};
    /** テキスト編集用スクラッチの格納フォルダ（KeepPluginから注入される） */
    this.scratchFolder = DEFAULT_SCRATCH_FOLDER;
    /** 新規作成ボタンの既定作成先フォルダ（KeepPluginから注入される・空欄はVault直下） */
    this.newFileFolder = "";
    this.activeTextSession = null;
    /** ページネーション・キャッシュ用 */
    this.renderLimit = RENDER_INITIAL_LIMIT;
    this.lastFilterKey = "";
    this.displayPinned = [];
    this.displayUnpinned = [];
    this.displayContentCache = /* @__PURE__ */ new Map();
    this.unpinnedGridEl = null;
    this.moreSentinelEl = null;
    this.moreObserver = null;
    this.searchWrapperEl = null;
    this.lastFolderPaths = null;
    this.lastTagList = null;
    this.lastFolderValue = "\0";
    this.lastTagValue = "\0";
    this.normalizedScratchCache = DEFAULT_SCRATCH_FOLDER;
    this.normalizedScratchSource = null;
    this.selectedFolder = "";
    this.selectedTag = "";
    this.searchQuery = "";
    this.isRandomMode = false;
    this.randomFiles = [];
    this.canvasSourcePath = null;
  }
  getViewType() {
    return KEEP_VIEW_TYPE;
  }
  getDisplayText() {
    return "Note masonry";
  }
  getIcon() {
    return "layout-grid";
  }
  async onClose() {
    this.disconnectMoreObserver();
    if (this.renderTimeout) {
      clearTimeout(this.renderTimeout);
      this.renderTimeout = null;
    }
  }
  getState() {
    return {
      ...super.getState(),
      selectedFolder: this.selectedFolder,
      selectedTag: this.selectedTag,
      searchQuery: this.searchQuery,
      canvasSourcePath: this.canvasSourcePath
    };
  }
  isCanvasMode() {
    return !!this.canvasSourcePath;
  }
  async setState(state, result) {
    if (typeof state.selectedFolder === "string") {
      this.selectedFolder = state.selectedFolder;
    }
    if (typeof state.selectedTag === "string") {
      this.selectedTag = state.selectedTag;
      this.hasAppliedDefaultTagFilter = true;
    }
    if (typeof state.searchQuery === "string") {
      this.searchQuery = state.searchQuery;
    }
    if (typeof state.canvasSourcePath === "string" && state.canvasSourcePath) {
      this.canvasSourcePath = state.canvasSourcePath;
    } else if (state.canvasSourcePath === null || state.canvasSourcePath === "") {
      this.canvasSourcePath = null;
    }
    this.isRandomMode = false;
    this.randomFiles = [];
    this.canvasFocusCycle = {};
    await super.setState(state, result);
    this.updateCanvasModeUI();
    if (this.searchInput && typeof this.searchQuery === "string") {
      this.searchInput.value = this.searchQuery;
      this.updateSearchVisibility();
    }
    this.requestRender();
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("keep-view-container");
    const filterContainer = container.createEl("div", { cls: "keep-filter-container" });
    this.filterContainer = filterContainer;
    const leftFilters = filterContainer.createEl("div", { cls: "keep-filter-left" });
    this.leftFilters = leftFilters;
    this.folderSelect = leftFilters.createEl("select", { cls: "keep-select" });
    this.folderSelect.addEventListener("change", (e) => {
      this.selectedFolder = e.target.value;
      this.adjustSelectWidth(this.folderSelect);
      this.exitRandomMode();
      this.requestRender();
    });
    this.tagSelect = leftFilters.createEl("select", { cls: "keep-select" });
    this.tagSelect.addEventListener("change", (e) => {
      this.selectedTag = e.target.value;
      this.adjustSelectWidth(this.tagSelect);
      this.exitRandomMode();
      this.requestRender();
    });
    this.randomButton = filterContainer.createEl("button", {
      cls: "keep-random-button",
      attr: { "aria-label": "Show 15 random notes", "title": "\u30E9\u30F3\u30C0\u30E0\u306B15\u4EF6\u8868\u793A" }
    });
    (0, import_obsidian.setIcon)(this.randomButton, "shuffle");
    this.randomButton.addEventListener("click", () => {
      this.showRandomFiles();
    });
    const searchContainer = filterContainer.createEl("div", { cls: "keep-search-container" });
    const searchWrapper = searchContainer.createEl("div", { cls: "keep-search-wrapper" });
    const searchIconWrapper = searchWrapper.createEl("div", { cls: "keep-search-icon" });
    (0, import_obsidian.setIcon)(searchIconWrapper, "search");
    this.searchInput = searchWrapper.createEl("input", {
      cls: "keep-search-input",
      attr: {
        type: "text",
        placeholder: "Search notes..."
      }
    });
    this.searchInput.value = this.searchQuery;
    this.searchInput.addEventListener("input", (e) => {
      this.searchQuery = e.target.value;
      this.updateSearchVisibility();
      this.exitRandomMode();
      this.requestRender();
    });
    this.searchInput.addEventListener("focus", () => {
      searchWrapper.addClass("is-focused");
    });
    this.searchInput.addEventListener("blur", () => {
      searchWrapper.removeClass("is-focused");
    });
    this.updateSearchVisibility();
    const createButton = filterContainer.createEl("button", {
      cls: "keep-create-button"
    });
    this.createButton = createButton;
    (0, import_obsidian.setIcon)(createButton, "plus");
    createButton.addEventListener("click", () => {
      this.openNoteModal(null, { selectedFolder: this.getEffectiveNewFileFolder(), selectedTag: this.selectedTag });
    });
    this.canvasBanner = container.createEl("div", { cls: "keep-canvas-banner" });
    this.canvasBanner.hide();
    this.gridContainer = container.createEl("div", { cls: "keep-grid-wrapper" });
    this.searchWrapperEl = searchWrapper;
    this.registerEvent(this.app.vault.on("create", (f) => {
      if (f instanceof import_obsidian.TFile && this.isScratchFile(f))
        return;
      this.requestRender(300);
    }));
    this.registerEvent(this.app.vault.on("modify", (f) => {
      if (f instanceof import_obsidian.TFile && this.isScratchFile(f))
        return;
      if (f instanceof import_obsidian.TFile && f.extension === "canvas" && !this.isCanvasMode())
        return;
      this.requestRender(600);
    }));
    this.registerEvent(this.app.vault.on("delete", (f) => {
      if (f instanceof import_obsidian.TFile && this.isScratchFile(f))
        return;
      this.requestRender(300);
    }));
    this.registerEvent(this.app.vault.on("rename", () => this.requestRender(300)));
    this.registerEvent(this.app.metadataCache.on("changed", (f) => {
      if (f instanceof import_obsidian.TFile && this.isScratchFile(f))
        return;
      this.requestRender(600);
    }));
    this.updateCanvasModeUI();
    void this.cleanupLegacyScratchFiles();
    await this.renderGrid();
  }
  /** canvasモードではフォルダ/タグ/ランダム/新規作成を隠し、検索バーのみ＋バナーを表示する */
  updateCanvasModeUI() {
    const canvasMode = this.isCanvasMode();
    if (this.leftFilters) {
      this.leftFilters.style.display = canvasMode ? "none" : "";
    }
    if (this.randomButton) {
      this.randomButton.style.display = canvasMode ? "none" : "";
    }
    if (this.createButton) {
      this.createButton.style.display = canvasMode ? "none" : "";
    }
    if (this.canvasBanner) {
      this.canvasBanner.empty();
      if (canvasMode && this.canvasSourcePath) {
        this.canvasBanner.show();
        const label = this.canvasBanner.createEl("span", {
          cls: "keep-canvas-banner-label",
          text: `Filtered by ${this.canvasSourcePath}`
        });
        label.setAttr("title", this.canvasSourcePath);
        const clearBtn = this.canvasBanner.createEl("button", {
          cls: "keep-canvas-banner-clear",
          attr: { "aria-label": "Clear canvas filter" }
        });
        (0, import_obsidian.setIcon)(clearBtn, "x");
        clearBtn.addEventListener("click", () => {
          this.canvasSourcePath = null;
          this.canvasFocusCycle = {};
          this.updateCanvasModeUI();
          this.requestRender();
        });
      } else {
        this.canvasBanner.hide();
      }
    }
  }
  getCanvasSourceFile() {
    if (!this.canvasSourcePath)
      return null;
    const f = this.app.vault.getAbstractFileByPath(this.canvasSourcePath);
    return f instanceof import_obsidian.TFile ? f : null;
  }
  /** .canvas JSONからfile/textノードを取り出す（link/groupは除外）。配置順維持のためnodeIndexを付与する */
  async loadCanvasGridItems(canvasFile) {
    let raw = "";
    try {
      raw = await this.app.vault.read(canvasFile);
    } catch (e) {
      return [];
    }
    try {
      const data = JSON.parse(raw);
      if (!data || !Array.isArray(data.nodes))
        return [];
      const fileSeen = /* @__PURE__ */ new Set();
      const fileByKey = /* @__PURE__ */ new Map();
      const texts = [];
      data.nodes.forEach((n, index) => {
        const node = n;
        if (!node || typeof node.type !== "string")
          return;
        if (node.type === "file" && typeof node.file === "string" && node.file) {
          let f = this.app.vault.getAbstractFileByPath(node.file);
          if (!(f instanceof import_obsidian.TFile)) {
            try {
              const dest = this.app.metadataCache.getFirstLinkpathDest(node.file, canvasFile.path);
              if (dest instanceof import_obsidian.TFile)
                f = dest;
            } catch (e) {
            }
          }
          if (f instanceof import_obsidian.TFile && !fileSeen.has(f.path)) {
            fileSeen.add(f.path);
            fileByKey.set(f.path, { file: f, nodeIndex: index });
          }
        } else if (node.type === "text" && typeof node.id === "string" && typeof node.text === "string") {
          texts.push({
            kind: "text",
            nodeId: node.id,
            text: node.text,
            color: typeof node.color === "string" ? node.color : void 0,
            nodeIndex: index
          });
        }
      });
      const items = [];
      for (const { file, nodeIndex } of fileByKey.values()) {
        items.push({ kind: "file", file, nodeIndex });
      }
      for (const t of texts)
        items.push(t);
      items.sort((a, b) => a.nodeIndex - b.nodeIndex);
      return items;
    } catch (e) {
      return [];
    }
  }
  isMarkdownFile(file) {
    return file.extension === "md";
  }
  updateSearchVisibility() {
    var _a;
    const searchWrapper = (_a = this.searchWrapperEl) != null ? _a : this.containerEl.querySelector(".keep-search-wrapper");
    if (!this.searchWrapperEl && searchWrapper)
      this.searchWrapperEl = searchWrapper;
    if (searchWrapper) {
      if (this.searchQuery) {
        searchWrapper.addClass("has-value");
      } else {
        searchWrapper.removeClass("has-value");
      }
    }
  }
  /**
   * 編集モーダルを開く共通ヘルパー。開いている間は requestRender を抑止して
   * 背後のカードViewが編集中にちらつかないようにし、閉じた後に1回だけ再描画する。
   */
  openNoteModal(file, opts = {}) {
    var _a, _b, _c;
    _KeepView.openModalCount++;
    let closed = false;
    const doClose = () => {
      var _a2;
      if (closed)
        return;
      closed = true;
      _KeepView.openModalCount = Math.max(0, _KeepView.openModalCount - 1);
      try {
        (_a2 = opts.onClosed) == null ? void 0 : _a2.call(opts);
      } finally {
        if (opts.renderOnClose !== false)
          this.requestRender();
      }
    };
    try {
      new NoteEditModal(this.app, file, this.leaf, doClose, (_a = opts.selectedFolder) != null ? _a : "", (_b = opts.selectedTag) != null ? _b : "", (_c = opts.hideTitle) != null ? _c : false).open();
    } catch (e) {
      doClose();
      throw e;
    }
  }
  requestRender(delay = 300) {
    if (_KeepView.openModalCount > 0)
      return;
    if (this.renderTimeout) {
      clearTimeout(this.renderTimeout);
    }
    this.renderTimeout = setTimeout(() => {
      this.renderTimeout = null;
      if (this.isRendering) {
        this.pendingRender = true;
        return;
      }
      void this.renderGrid();
    }, delay);
  }
  applyDefaultTagFilter() {
    var _a;
    if (this.hasAppliedDefaultTagFilter)
      return;
    if (this.selectedTag) {
      this.hasAppliedDefaultTagFilter = true;
      return;
    }
    const tags = Object.keys((_a = this.app.metadataCache.getTags()) != null ? _a : {}).sort();
    if (tags.length === 0)
      return;
    if (tags.includes(DEFAULT_TAG_FILTER)) {
      this.selectedTag = DEFAULT_TAG_FILTER;
    } else {
      this.selectedTag = tags[0];
    }
    this.hasAppliedDefaultTagFilter = true;
  }
  showRandomFiles() {
    const all = this.app.vault.getMarkdownFiles().filter((f) => !this.isScratchFile(f));
    for (let i = all.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [all[i], all[j]] = [all[j], all[i]];
    }
    this.randomFiles = all.slice(0, RANDOM_FILE_COUNT);
    this.isRandomMode = true;
    this.updateRandomButtonState();
    this.requestRender();
  }
  exitRandomMode() {
    if (!this.isRandomMode)
      return;
    this.isRandomMode = false;
    this.randomFiles = [];
    this.updateRandomButtonState();
  }
  updateRandomButtonState() {
    if (this.randomButton) {
      this.randomButton.toggleClass("is-active", this.isRandomMode);
    }
  }
  isSameStringArray(a, b) {
    if (!a || a.length !== b.length)
      return false;
    for (let i = 0; i < b.length; i++) {
      if (a[i] !== b[i])
        return false;
    }
    return true;
  }
  updateFilterUI() {
    const folders = this.app.vault.getAllLoadedFiles().filter((f) => f instanceof import_obsidian.TFolder);
    const tags = Object.keys(this.app.metadataCache.getTags()).sort();
    const folderPaths = folders.map((f) => f.path);
    if (!this.isSameStringArray(this.lastFolderPaths, folderPaths) || this.folderSelect.options.length !== folders.length + 1) {
      const currentFolder = this.selectedFolder;
      this.folderSelect.empty();
      this.folderSelect.createEl("option", { value: "", text: "All folders" });
      folders.forEach((f) => {
        if (f.path === "/")
          return;
        const option = this.folderSelect.createEl("option", { value: f.path, text: f.path });
        if (f.path === currentFolder)
          option.selected = true;
      });
      this.lastFolderPaths = folderPaths;
      this.lastFolderValue = "\0";
    }
    if (!this.isSameStringArray(this.lastTagList, tags) || this.tagSelect.options.length !== tags.length + 1) {
      const currentTag = this.selectedTag;
      this.tagSelect.empty();
      this.tagSelect.createEl("option", { value: "", text: "All tags" });
      tags.forEach((t) => {
        const option = this.tagSelect.createEl("option", { value: t, text: t });
        if (t === currentTag)
          option.selected = true;
      });
      this.lastTagList = tags.slice();
      this.lastTagValue = "\0";
    }
    if (this.folderSelect.value !== this.selectedFolder) {
      this.folderSelect.value = this.selectedFolder;
    }
    if (this.lastFolderValue !== this.selectedFolder) {
      this.adjustSelectWidth(this.folderSelect);
      this.lastFolderValue = this.selectedFolder;
    }
    if (this.tagSelect.value !== this.selectedTag) {
      this.tagSelect.value = this.selectedTag;
    }
    if (this.lastTagValue !== this.selectedTag) {
      this.adjustSelectWidth(this.tagSelect);
      this.lastTagValue = this.selectedTag;
    }
  }
  adjustSelectWidth(select) {
    if (!select || select.options.length === 0)
      return;
    const selected = select.options[select.selectedIndex];
    if (!selected)
      return;
    const cacheKey = selected.text;
    if (select.dataset.lastWidthFor === cacheKey)
      return;
    const tempSpan = document.createElement("span");
    tempSpan.setCssProps({
      "visibility": "hidden",
      "position": "absolute",
      "white-space": "nowrap"
    });
    const computedStyle = window.getComputedStyle(select);
    tempSpan.setCssProps({
      "font-size": computedStyle.fontSize,
      "font-family": computedStyle.fontFamily
    });
    tempSpan.innerText = cacheKey;
    document.body.appendChild(tempSpan);
    const textWidth = tempSpan.getBoundingClientRect().width;
    document.body.removeChild(tempSpan);
    select.style.width = `${textWidth + 20}px`;
    select.dataset.lastWidthFor = cacheKey;
  }
  /** フィルタ条件のキー。変わったときだけページネーションをリセットする */
  getFilterKey() {
    var _a;
    return `${this.selectedFolder}
${this.selectedTag}
${this.searchQuery}
${this.isRandomMode ? "R" : ""}
${(_a = this.canvasSourcePath) != null ? _a : ""}`;
  }
  /** frontmatterを除いた本文を取り出す（検索・スニペット共通） */
  stripFrontmatter(content, file) {
    try {
      const cache = this.app.metadataCache.getFileCache(file);
      if (cache == null ? void 0 : cache.frontmatterPosition) {
        return content.substring(cache.frontmatterPosition.end.offset);
      }
    } catch (e) {
    }
    if (content.charCodeAt(0) === 45 && content.startsWith("---")) {
      return content.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n/, "");
    }
    return content;
  }
  async readCachedWithCache(file, cache) {
    const hit = cache.get(file.path);
    if (hit !== void 0)
      return hit;
    const content = await this.app.vault.cachedRead(file);
    if (cache.size > 500) {
      const first = cache.keys().next();
      if (!first.done)
        cache.delete(first.value);
    }
    cache.set(file.path, content);
    return content;
  }
  /**
   * 本文検索。basename一致を先に確定させ、残りだけ本文読み＋バッチ処理する。
   * 読み込んだ本文はcontentCacheに残し、カード描画での二重読みを避ける。
   */
  async filterBySearchQuery(files, query, contentCache) {
    const matched = [];
    const needContent = [];
    const matchedPaths = /* @__PURE__ */ new Set();
    for (const f of files) {
      if (f.basename.toLowerCase().includes(query) || f.path.toLowerCase().includes(query)) {
        matched.push(f);
        matchedPaths.add(f.path);
      } else {
        needContent.push(f);
      }
    }
    if (needContent.length === 0)
      return matched;
    const contentMatched = [];
    for (let i = 0; i < needContent.length; i += SEARCH_CONTENT_BATCH) {
      const slice = needContent.slice(i, i + SEARCH_CONTENT_BATCH);
      const results = await Promise.all(slice.map(async (f) => {
        try {
          const content = await this.readCachedWithCache(f, contentCache);
          const body = this.stripFrontmatter(content, f);
          return body.toLowerCase().includes(query);
        } catch (e) {
          return false;
        }
      }));
      for (let j = 0; j < slice.length; j++) {
        if (results[j])
          contentMatched.push(slice[j]);
      }
      if (i + SEARCH_CONTENT_BATCH < needContent.length) {
        await new Promise((r) => setTimeout(r, 0));
      }
    }
    if (contentMatched.length === 0)
      return matched;
    const contentSet = new Set(contentMatched.map((f) => f.path));
    const out = [];
    for (const f of files) {
      if (matchedPaths.has(f.path) || contentSet.has(f.path))
        out.push(f);
    }
    return out;
  }
  async renderGrid() {
    var _a;
    if (this.isRendering) {
      this.pendingRender = true;
      return;
    }
    this.isRendering = true;
    try {
      this.updateCanvasModeUI();
      if (this.isCanvasMode()) {
        await this.renderCanvasGrid();
        return;
      }
      this.applyDefaultTagFilter();
      this.updateFilterUI();
      this.updateRandomButtonState();
      const filterKey = this.getFilterKey();
      if (filterKey !== this.lastFilterKey) {
        this.renderLimit = RENDER_INITIAL_LIMIT;
        this.lastFilterKey = filterKey;
      }
      let files;
      const contentCache = /* @__PURE__ */ new Map();
      if (this.isRandomMode) {
        const allMarkdown = this.app.vault.getMarkdownFiles();
        const existingPaths = new Set(allMarkdown.map((f) => f.path));
        files = this.randomFiles.filter((f) => existingPaths.has(f.path) && !this.isScratchFile(f));
      } else {
        let filtered = this.app.vault.getMarkdownFiles().filter((f) => !this.isScratchFile(f));
        if (this.selectedFolder) {
          const prefix = this.selectedFolder + "/";
          filtered = filtered.filter((f) => {
            var _a2, _b;
            return ((_a2 = f.parent) == null ? void 0 : _a2.path) === this.selectedFolder || ((_b = f.parent) == null ? void 0 : _b.path.startsWith(prefix));
          });
        }
        if (this.selectedTag) {
          const tag = this.selectedTag;
          filtered = filtered.filter((f) => {
            const cache = this.app.metadataCache.getFileCache(f);
            const tags = cache ? (0, import_obsidian.getAllTags)(cache) || [] : [];
            return tags.includes(tag);
          });
        }
        if (this.searchQuery) {
          const query = this.searchQuery.toLowerCase();
          filtered = await this.filterBySearchQuery(filtered, query, contentCache);
        }
        files = filtered;
      }
      files.sort((a, b) => b.stat.mtime - a.stat.mtime);
      const pinnedFiles = [];
      const unpinnedFiles = [];
      for (const file of files) {
        const cache = this.app.metadataCache.getFileCache(file);
        const isPinned = ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.pinned) === true;
        if (isPinned)
          pinnedFiles.push(file);
        else
          unpinnedFiles.push(file);
      }
      this.displayPinned = pinnedFiles;
      this.displayUnpinned = unpinnedFiles;
      this.displayContentCache = contentCache;
      this.disconnectMoreObserver();
      this.gridContainer.empty();
      this.unpinnedGridEl = null;
      this.moreSentinelEl = null;
      if (pinnedFiles.length > 0) {
        this.gridContainer.createEl("h3", { text: "Pinned", cls: "keep-section-title" });
        const pinnedGrid = this.gridContainer.createEl("div", { cls: "keep-grid" });
        await this.renderCards(pinnedFiles, pinnedGrid, contentCache);
        if (unpinnedFiles.length > 0) {
          this.gridContainer.createEl("h3", { text: "Others", cls: "keep-section-title keep-section-title-others" });
        }
      }
      const unpinnedGrid = this.gridContainer.createEl("div", { cls: "keep-grid" });
      this.unpinnedGridEl = unpinnedGrid;
      const visible = unpinnedFiles.slice(0, Math.max(0, this.renderLimit - pinnedFiles.length));
      await this.renderCards(visible, unpinnedGrid, contentCache);
      this.setupMoreUI(unpinnedFiles.length, visible.length);
    } finally {
      this.isRendering = false;
      if (this.pendingRender) {
        this.pendingRender = false;
        this.requestRender(100);
      }
    }
  }
  disconnectMoreObserver() {
    if (this.moreObserver) {
      try {
        this.moreObserver.disconnect();
      } catch (e) {
      }
      this.moreObserver = null;
    }
  }
  /** 残り件数表示＋自動追加（IntersectionObserver）で初回描画を軽く保つ */
  setupMoreUI(total, rendered) {
    const rest = total - rendered;
    if (rest <= 0)
      return;
    const moreWrap = this.gridContainer.createEl("div", { cls: "keep-more-wrap" });
    const btn = moreWrap.createEl("button", {
      cls: "keep-more-button",
      text: `\u3055\u3089\u306B\u8868\u793A (${rendered}/${total})`
    });
    btn.addEventListener("click", () => void this.renderMore());
    this.moreSentinelEl = moreWrap;
    try {
      this.moreObserver = new IntersectionObserver((entries) => {
        for (const e of entries) {
          if (e.isIntersecting) {
            void this.renderMore();
            break;
          }
        }
      }, { rootMargin: "600px" });
      this.moreObserver.observe(moreWrap);
    } catch (e) {
    }
  }
  async renderMore() {
    if (this.isRendering)
      return;
    if (!this.unpinnedGridEl || !this.moreSentinelEl)
      return;
    const total = this.displayUnpinned.length;
    const rendered = this.unpinnedGridEl.children.length;
    if (rendered >= total) {
      this.moreSentinelEl.remove();
      this.moreSentinelEl = null;
      this.disconnectMoreObserver();
      return;
    }
    this.isRendering = true;
    try {
      this.renderLimit += RENDER_MORE_STEP;
      const next = this.displayUnpinned.slice(rendered, rendered + RENDER_MORE_STEP);
      await this.renderCards(next, this.unpinnedGridEl, this.displayContentCache);
      const now = this.unpinnedGridEl.children.length;
      if (now >= total) {
        this.moreSentinelEl.remove();
        this.moreSentinelEl = null;
        this.disconnectMoreObserver();
      } else {
        const btn = this.moreSentinelEl.querySelector(".keep-more-button");
        if (btn)
          btn.setText(`\u3055\u3089\u306B\u8868\u793A (${now}/${total})`);
      }
    } finally {
      this.isRendering = false;
      if (this.pendingRender) {
        this.pendingRender = false;
        this.requestRender(100);
      }
    }
  }
  /** canvasモード専用: そのcanvas内のfile/textノードを配置順で表示し、検索バーで絞り込む */
  async renderCanvasGrid() {
    this.gridContainer.empty();
    const canvasFile = this.getCanvasSourceFile();
    if (!canvasFile || canvasFile.extension !== "canvas") {
      this.gridContainer.createEl("div", {
        text: this.canvasSourcePath ? `Canvas not found: ${this.canvasSourcePath}` : "No canvas selected.",
        cls: "keep-empty-message"
      });
      return;
    }
    let items = await this.loadCanvasGridItems(canvasFile);
    const canvasContentCache = /* @__PURE__ */ new Map();
    if (this.searchQuery) {
      const query = this.searchQuery.toLowerCase();
      const out = [];
      for (let i = 0; i < items.length; i += SEARCH_CONTENT_BATCH) {
        const slice = items.slice(i, i + SEARCH_CONTENT_BATCH);
        const results = await Promise.all(slice.map((item) => {
          if (item.kind === "file")
            return this.matchesCanvasSearch(item.file, query, canvasContentCache);
          return Promise.resolve(item.text.toLowerCase().includes(query));
        }));
        for (let j = 0; j < slice.length; j++) {
          if (results[j])
            out.push(slice[j]);
        }
        if (i + SEARCH_CONTENT_BATCH < items.length) {
          await new Promise((r) => setTimeout(r, 0));
        }
      }
      items = out;
    }
    if (items.length === 0) {
      this.gridContainer.createEl("div", {
        text: "\u3053\u306E\u30AD\u30E3\u30F3\u30D0\u30B9\u306B\u8868\u793A\u3067\u304D\u308B\u30D5\u30A1\u30A4\u30EB\u304C\u3042\u308A\u307E\u305B\u3093\u3002",
        cls: "keep-empty-message"
      });
      return;
    }
    const grid = this.gridContainer.createEl("div", { cls: "keep-grid" });
    await this.renderCanvasCards(items, grid, canvasContentCache);
  }
  async matchesCanvasSearch(file, query, contentCache) {
    if (file.basename.toLowerCase().includes(query))
      return true;
    if (file.path.toLowerCase().includes(query))
      return true;
    if (!this.isMarkdownFile(file))
      return false;
    try {
      const content = contentCache ? await this.readCachedWithCache(file, contentCache) : await this.app.vault.cachedRead(file);
      const body = this.stripFrontmatter(content, file);
      return body.toLowerCase().includes(query);
    } catch (e) {
      return false;
    }
  }
  /** canvasモード専用の混在グリッド描画（配置順）。fileは既存カード、textはタイトルなし＋その場編集 */
  async renderCanvasCards(items, container, contentCache) {
    const filesOnly = items.every((i) => i.kind === "file");
    if (filesOnly) {
      await this.renderCards(items.map((i) => i.file), container, contentCache);
      return;
    }
    const cache = contentCache != null ? contentCache : /* @__PURE__ */ new Map();
    const fragment = document.createDocumentFragment();
    let sinceYield = 0;
    for (const item of items) {
      if (item.kind === "file") {
        await this.buildCanvasFileCard(item.file, fragment, cache);
      } else {
        this.buildCanvasTextCard(item, fragment);
      }
      if (++sinceYield >= RENDER_YIELD_EVERY) {
        container.appendChild(fragment);
        await new Promise((r) => setTimeout(r, 0));
        sinceYield = 0;
      }
    }
    if (fragment.childNodes.length > 0)
      container.appendChild(fragment);
  }
  /** canvasモードのファイルカード1件分（renderCardsのcanvas分岐と同等。split残存／pin・menu・DnDなし） */
  async buildCanvasFileCard(file, fragment, contentCache) {
    const isMd = this.isMarkdownFile(file);
    let contentWithoutFrontmatter = "";
    if (isMd) {
      try {
        const content = contentCache ? await this.readCachedWithCache(file, contentCache) : await this.app.vault.cachedRead(file);
        contentWithoutFrontmatter = this.stripFrontmatter(content, file).trim();
      } catch (e) {
        contentWithoutFrontmatter = "";
      }
    }
    const images = [];
    let match;
    if (isMd) {
      const imageRegex = /!\[.*?\]\((.*?)\)|!\[\[(.*?)\]\]/g;
      while ((match = imageRegex.exec(contentWithoutFrontmatter)) !== null && images.length < 2) {
        const url = match[1] || match[2];
        if (url)
          images.push(url);
      }
    }
    const resolvedImages = images.map((img) => {
      if (img.startsWith("http://") || img.startsWith("https://") || img.startsWith("app://") || img.startsWith("data:")) {
        return img;
      }
      const linkedFile = this.app.metadataCache.getFirstLinkpathDest(img, file.path);
      if (linkedFile)
        return this.app.vault.getResourcePath(linkedFile);
      return null;
    }).filter((img) => img !== null);
    if (!isMd && this.isImageFile(file)) {
      try {
        resolvedImages.unshift(this.app.vault.getResourcePath(file));
      } catch (e) {
      }
    }
    const snippetText = isMd ? contentWithoutFrontmatter.replace(/!\[.*?\]\(.*?\)|!\[\[.*?\]\]/g, "").trim() : `${file.extension.toUpperCase()} \u2022 ${file.path}`;
    const snippet = isMd ? snippetText.substring(0, 250) + (snippetText.length > 250 ? "..." : "") : snippetText;
    const card = fragment.createEl("div", { cls: "keep-card" });
    card.draggable = false;
    if (resolvedImages.length > 0) {
      const imgContainer = card.createEl("div", { cls: `keep-card-images keep-card-images-${Math.min(resolvedImages.length, 2)}` });
      resolvedImages.slice(0, 2).forEach((img) => {
        const imgEl = imgContainer.createEl("img", { attr: { src: img } });
        imgEl.draggable = false;
      });
    }
    const splitBtn = card.createEl("button", {
      cls: "keep-split-btn",
      attr: { "aria-label": "Open in split view" }
    });
    (0, import_obsidian.setIcon)(splitBtn, "panel-right");
    const splitSvg = splitBtn.querySelector("svg");
    if (splitSvg) {
      splitSvg.setAttribute("fill", "none");
      splitSvg.setAttribute("stroke", "currentColor");
    }
    splitBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      const leaf = this.app.workspace.getLeaf("split");
      void leaf.openFile(file);
    });
    if (file.basename) {
      card.createEl("h3", { text: file.basename, cls: "keep-card-title" });
    }
    if (snippet) {
      card.createEl("div", { text: snippet, cls: "keep-card-snippet" });
    }
    card.addEventListener("click", (e) => {
      if (e.metaKey || e.ctrlKey) {
        e.preventDefault();
        e.stopPropagation();
        void this.focusCanvasNode(file);
        return;
      }
      if (isMd) {
        this.openNoteModal(file);
      } else {
        const leaf = this.app.workspace.getLeaf("tab");
        void leaf.openFile(file);
      }
    });
  }
  /** テキストカード1件分。タイトルなし・全文スニペットのみ。通常クリックで大モーダル編集、Cmd+クリックでフォーカス */
  buildCanvasTextCard(item, fragment) {
    const card = fragment.createEl("div", { cls: "keep-card keep-text-card" });
    card.draggable = false;
    card.setAttr("data-canvas-node-id", item.nodeId);
    const body = item.text.trim();
    const snippet = body.length > 250 ? body.substring(0, 250) + "..." : body;
    card.createEl("div", {
      text: snippet || "(\u7A7A\u306E\u30C6\u30AD\u30B9\u30C8\u30AB\u30FC\u30C9)",
      cls: "keep-card-snippet keep-text-snippet"
    });
    card.addEventListener("click", (e) => {
      if (e.metaKey || e.ctrlKey) {
        e.preventDefault();
        e.stopPropagation();
        void this.focusCanvasNodeById(item.nodeId);
        return;
      }
      void this.openCanvasTextModal(item);
    });
  }
  getScratchFolder() {
    if (this.normalizedScratchSource !== this.scratchFolder) {
      this.normalizedScratchCache = normalizeScratchFolder(this.scratchFolder);
      this.normalizedScratchSource = this.scratchFolder;
    }
    return this.normalizedScratchCache;
  }
  /**
   * 新規作成ボタンの実効的な作成先フォルダを返す。
   * フォルダで絞り込み中はそのフォルダを優先し、未絞り込み(All folders)のときだけ
   * 設定の既定フォルダを使う。空文字はVault直下を意味する。
   */
  getEffectiveNewFileFolder() {
    if (this.selectedFolder)
      return this.selectedFolder;
    return normalizeNewFileFolder(this.newFileFolder);
  }
  isScratchFile(f) {
    if (f.name.endsWith(".masonry-scratch.md"))
      return true;
    const folder = this.getScratchFolder();
    return folder ? f.path === folder || f.path.startsWith(folder + "/") : false;
  }
  async ensureScratchFolder(folder) {
    if (!folder)
      return;
    const existing = this.app.vault.getAbstractFileByPath(folder);
    if (existing) {
      if (existing instanceof import_obsidian.TFolder)
        return;
      throw new Error(`Scratch folder path is occupied by a file: ${folder}`);
    }
    await this.app.vault.createFolder(folder);
  }
  getSharedScratchPath() {
    const folder = this.getScratchFolder();
    return folder ? `${folder}/${_KeepView.SHARED_SCRATCH_NAME}` : _KeepView.SHARED_SCRATCH_NAME;
  }
  /**
   * 全canvas共有の使い回しスクラッチファイルを取得する。なければ作成する。
   * 毎回の作成・削除は行わない。canvas名を含めない単一ファイルにすることで、
   * canvasリネームのたびに別ファイルが増殖する問題を防ぐ。
   * 編集はモーダル排他のため共有でも競合しない（残存セッションはflushで先に書き戻す）。
   */
  async getScratchFile() {
    const folder = this.getScratchFolder();
    await this.ensureScratchFolder(folder);
    const path = this.getSharedScratchPath();
    const existing = this.app.vault.getAbstractFileByPath(path);
    if (existing instanceof import_obsidian.TFile)
      return existing;
    if (existing) {
      throw new Error(`Scratch file path is occupied: ${path}`);
    }
    return await this.app.vault.create(path, "");
  }
  /**
   * 旧形式（`<canvas名>.masonry-scratch.md`）の残骸をゴミ箱に移動する。
   * canvasリネームのたびに増殖した分を回収する。セッション中1回だけ実行。
   */
  async cleanupLegacyScratchFiles() {
    if (_KeepView.legacyScratchCleaned)
      return;
    _KeepView.legacyScratchCleaned = true;
    try {
      const stale = this.app.vault.getFiles().filter((f) => f.name.endsWith(".masonry-scratch.md") && f.name !== _KeepView.SHARED_SCRATCH_NAME);
      for (const f of stale) {
        try {
          await this.app.fileManager.trashFile(f);
        } catch (e) {
          console.warn("Cleanup legacy scratch failed", f.path, e);
        }
      }
      if (stale.length > 0) {
        new import_obsidian.Notice(`\u53E4\u3044\u30B9\u30AF\u30E9\u30C3\u30C1\u30D5\u30A1\u30A4\u30EB${stale.length}\u4EF6\u3092\u30B4\u30DF\u7BB1\u306B\u79FB\u52D5\u3057\u307E\u3057\u305F`);
      }
    } catch (e) {
      console.warn("Cleanup legacy scratch failed", e);
    }
  }
  /**
   * テキストノードを通常ファイルと同じ大モーダルで編集する。
   * スクラッチに本文を流し込んでNoteEditModalで開き、close時にcanvasへ書き戻す。
   */
  async openCanvasTextModal(item) {
    try {
      const canvasFile = this.getCanvasSourceFile();
      if (!canvasFile) {
        new import_obsidian.Notice("Canvas\u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093");
        return;
      }
      await this.flushActiveTextSession();
      const scratch = await this.getScratchFile();
      let current = "";
      try {
        current = await this.app.vault.read(scratch);
      } catch (e) {
        current = "";
      }
      if (current !== item.text) {
        await this.app.vault.modify(scratch, item.text);
      }
      const baseText = item.text;
      this.activeTextSession = { canvasPath: canvasFile.path, nodeId: item.nodeId, baseText };
      this.openNoteModal(scratch, {
        hideTitle: true,
        renderOnClose: false,
        onClosed: () => {
          void this.onTextModalClose(canvasFile, item.nodeId, baseText);
        }
      });
    } catch (e) {
      console.error("Open canvas text modal failed", e);
      new import_obsidian.Notice("\u30C6\u30AD\u30B9\u30C8\u306E\u7DE8\u96C6\u3092\u958B\u3051\u307E\u305B\u3093\u3067\u3057\u305F");
    }
  }
  /** モーダルclose時の書き戻し。エディタの自動保存を待ってからスクラッチ→canvasへ反映する */
  async onTextModalClose(canvasFile, nodeId, baseText) {
    var _a;
    try {
      await new Promise((r) => window.setTimeout(r, 300));
      const scratch = this.app.vault.getAbstractFileByPath(this.getSharedScratchPath());
      if (scratch instanceof import_obsidian.TFile) {
        let scratchText = "";
        try {
          scratchText = await this.app.vault.read(scratch);
        } catch (e) {
          scratchText = "";
        }
        await this.writeScratchBackToNode(canvasFile, nodeId, baseText, scratchText);
      }
    } catch (e) {
      console.error("Save canvas text from modal failed", e);
      new import_obsidian.Notice("\u30C6\u30AD\u30B9\u30C8\u30AB\u30FC\u30C9\u306E\u66F4\u65B0\u306B\u5931\u6557\u3057\u307E\u3057\u305F");
    } finally {
      if (((_a = this.activeTextSession) == null ? void 0 : _a.nodeId) === nodeId) {
        this.activeTextSession = null;
      }
      this.requestRender();
    }
  }
  /** スクラッチ内容をcanvasノードへ書き戻す。canvas側でも変わっていれば上書き＋通知する */
  async writeScratchBackToNode(canvasFile, nodeId, baseText, scratchText) {
    const raw = await this.app.vault.read(canvasFile);
    const data = JSON.parse(raw);
    if (!data || !Array.isArray(data.nodes))
      return false;
    const node = data.nodes.find((n) => n && n.id === nodeId && n.type === "text");
    if (!node || typeof node.text !== "string")
      return false;
    if (node.text === scratchText)
      return true;
    if (node.text !== baseText) {
      new import_obsidian.Notice("Canvas\u5074\u3067\u3082\u5909\u66F4\u304C\u3042\u308A\u307E\u3057\u305F\u3002\u4E0A\u66F8\u304D\u3057\u307E\u3057\u305F");
    }
    node.text = scratchText;
    await this.app.vault.modify(canvasFile, JSON.stringify(data, null, 2));
    return true;
  }
  /** 残存セッションがあれば書き戻す（モーダル排他のため通常は空のはずだが安全のため） */
  async flushActiveTextSession() {
    const session = this.activeTextSession;
    if (!session)
      return;
    try {
      const canvasFile = this.app.vault.getAbstractFileByPath(session.canvasPath);
      if (!(canvasFile instanceof import_obsidian.TFile)) {
        this.activeTextSession = null;
        return;
      }
      const scratch = this.app.vault.getAbstractFileByPath(this.getSharedScratchPath());
      if (scratch instanceof import_obsidian.TFile) {
        const scratchText = await this.app.vault.read(scratch);
        await this.writeScratchBackToNode(canvasFile, session.nodeId, session.baseText, scratchText);
      }
    } catch (e) {
      console.error("Flush text session failed", e);
    } finally {
      this.activeTextSession = null;
    }
  }
  /** ノードID指定でキャンバス上のテキストカードへフォーカスする（単一ノード想定） */
  async focusCanvasNodeById(nodeId) {
    try {
      const canvasPath = this.canvasSourcePath;
      if (!canvasPath)
        return;
      const canvasFile = this.app.vault.getAbstractFileByPath(canvasPath);
      if (!(canvasFile instanceof import_obsidian.TFile)) {
        new import_obsidian.Notice(`Canvas not found: ${canvasPath}`);
        return;
      }
      const leaf = await this.ensureCanvasLeafOpen(canvasFile);
      if (!leaf) {
        new import_obsidian.Notice("Canvas\u3092\u958B\u3051\u307E\u305B\u3093\u3067\u3057\u305F");
        return;
      }
      const canvas = await this.waitForCanvasNodes(leaf);
      if (!(canvas == null ? void 0 : canvas.nodes)) {
        new import_obsidian.Notice("Canvas\u306E\u8AAD\u307F\u8FBC\u307F\u306B\u5931\u6557\u3057\u307E\u3057\u305F");
        return;
      }
      const node = canvas.nodes.get(nodeId);
      if (!node) {
        new import_obsidian.Notice("Canvas\u4E0A\u306B\u898B\u3064\u304B\u308A\u307E\u305B\u3093\uFF08\u672A\u4FDD\u5B58\u306E\u53EF\u80FD\u6027\u304C\u3042\u308A\u307E\u3059\uFF09");
        return;
      }
      this.applyCanvasFocus(canvas, node);
    } catch (e) {
      console.error("Focus canvas node failed", e);
      new import_obsidian.Notice("Canvas\u3078\u306E\u30D5\u30A9\u30FC\u30AB\u30B9\u306B\u5931\u6557\u3057\u307E\u3057\u305F");
    }
  }
  async renderCards(files, container, contentCache) {
    var _a;
    const fragment = document.createDocumentFragment();
    const canvasMode = this.isCanvasMode();
    let sinceYield = 0;
    for (const file of files) {
      const isMd = this.isMarkdownFile(file);
      let contentWithoutFrontmatter = "";
      let cache = null;
      if (isMd) {
        try {
          const content = contentCache ? await this.readCachedWithCache(file, contentCache) : await this.app.vault.cachedRead(file);
          cache = this.app.metadataCache.getFileCache(file);
          contentWithoutFrontmatter = this.stripFrontmatter(content, file).trim();
        } catch (e) {
          contentWithoutFrontmatter = "";
        }
      }
      const images = [];
      let match;
      if (isMd) {
        const imageRegex = /!\[.*?\]\((.*?)\)|!\[\[(.*?)\]\]/g;
        while ((match = imageRegex.exec(contentWithoutFrontmatter)) !== null && images.length < 2) {
          const url = match[1] || match[2];
          if (url) {
            images.push(url);
          }
        }
      }
      const resolvedImages = images.map((img) => {
        if (img.startsWith("http://") || img.startsWith("https://") || img.startsWith("app://") || img.startsWith("data:")) {
          return img;
        }
        const linkedFile = this.app.metadataCache.getFirstLinkpathDest(img, file.path);
        if (linkedFile) {
          return this.app.vault.getResourcePath(linkedFile);
        }
        return null;
      }).filter((img) => img !== null);
      if (!isMd && this.isImageFile(file)) {
        try {
          resolvedImages.unshift(this.app.vault.getResourcePath(file));
        } catch (e) {
        }
      }
      const snippetText = isMd ? contentWithoutFrontmatter.replace(/!\[.*?\]\(.*?\)|!\[\[.*?\]\]/g, "").trim() : `${file.extension.toUpperCase()} \u2022 ${file.path}`;
      const snippet = isMd ? snippetText.substring(0, 250) + (snippetText.length > 250 ? "..." : "") : snippetText;
      const card = fragment.createEl("div", { cls: "keep-card" });
      card.draggable = !canvasMode;
      let cardWasDragged = false;
      if (!canvasMode) {
        card.addEventListener("dragstart", (e) => {
          cardWasDragged = true;
          card.addClass("is-dragging");
          try {
            const dm = this.app.dragManager;
            if ((dm == null ? void 0 : dm.dragFile) && (dm == null ? void 0 : dm.onDragStart)) {
              const info = dm.dragFile(e, file);
              if (info)
                dm.onDragStart(e, info);
            } else if (dm == null ? void 0 : dm.dragFile) {
              dm.dragFile(e, file);
            } else if (e.dataTransfer) {
              e.dataTransfer.effectAllowed = "copy";
              try {
                e.dataTransfer.setData("text/plain", file.path);
              } catch (e2) {
              }
            }
          } catch (e2) {
          }
        });
        card.addEventListener("dragend", () => {
          card.removeClass("is-dragging");
          window.setTimeout(() => {
            cardWasDragged = false;
          }, 150);
        });
      }
      if (resolvedImages.length > 0) {
        const imgContainer = card.createEl("div", { cls: `keep-card-images keep-card-images-${Math.min(resolvedImages.length, 2)}` });
        resolvedImages.slice(0, 2).forEach((img) => {
          const imgEl = imgContainer.createEl("img", { attr: { src: img } });
          imgEl.draggable = false;
        });
      }
      const splitBtn = card.createEl("button", {
        cls: "keep-split-btn",
        attr: { "aria-label": "Open in split view" }
      });
      (0, import_obsidian.setIcon)(splitBtn, "panel-right");
      const splitSvg = splitBtn.querySelector("svg");
      if (splitSvg) {
        splitSvg.setAttribute("fill", "none");
        splitSvg.setAttribute("stroke", "currentColor");
      }
      splitBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        const leaf = this.app.workspace.getLeaf("split");
        void leaf.openFile(file);
      });
      if (!canvasMode) {
        const pinBtn = card.createEl("button", { cls: "keep-pin-btn" });
        (0, import_obsidian.setIcon)(pinBtn, "pin");
        const svg = pinBtn.querySelector("svg");
        if (svg) {
          svg.setAttribute("fill", "none");
          svg.setAttribute("stroke", "currentColor");
        }
        const isPinned = ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.pinned) === true;
        if (isPinned) {
          pinBtn.addClass("is-pinned");
          if (svg) {
            svg.setAttribute("fill", "currentColor");
          }
        }
        pinBtn.addEventListener("click", (e) => {
          e.stopPropagation();
          void this.app.fileManager.processFrontMatter(file, (fm) => {
            fm.pinned = !isPinned;
          });
        });
        const menuBtn = card.createEl("button", {
          cls: "keep-menu-btn",
          attr: { "aria-label": "Card menu" }
        });
        (0, import_obsidian.setIcon)(menuBtn, "more-horizontal");
        const menuSvg = menuBtn.querySelector("svg");
        if (menuSvg) {
          menuSvg.setAttribute("fill", "none");
          menuSvg.setAttribute("stroke", "currentColor");
        }
        menuBtn.addEventListener("click", (e) => {
          e.stopPropagation();
          const menu = new import_obsidian.Menu();
          menu.addItem((item) => {
            item.setTitle("Delete").setIcon("trash").onClick(() => {
              void this.app.fileManager.trashFile(file).then(() => {
                this.requestRender();
              });
            });
          });
          menu.showAtMouseEvent(e);
        });
      }
      if (file.basename) {
        card.createEl("h3", { text: file.basename, cls: "keep-card-title" });
      }
      if (snippet) {
        card.createEl("div", { text: snippet, cls: "keep-card-snippet" });
      }
      card.addEventListener("click", (e) => {
        if (cardWasDragged) {
          cardWasDragged = false;
          return;
        }
        if (canvasMode && (e.metaKey || e.ctrlKey)) {
          e.preventDefault();
          e.stopPropagation();
          void this.focusCanvasNode(file);
          return;
        }
        if (isMd) {
          this.openNoteModal(file);
        } else {
          const leaf = this.app.workspace.getLeaf("tab");
          void leaf.openFile(file);
        }
      });
      if (!canvasMode) {
        card.addEventListener("contextmenu", (e) => {
          e.preventDefault();
          e.stopPropagation();
          const menu = new import_obsidian.Menu();
          menu.addItem((item) => {
            item.setTitle("Send to Canvas").setIcon("layout-dashboard").onClick(() => void this.sendFileToCanvas(file));
          });
          menu.addItem((item) => {
            item.setTitle("Send to new Canvas").setIcon("plus").onClick(() => void this.createCanvasAndAdd(file));
          });
          menu.addSeparator();
          menu.addItem((item) => {
            item.setTitle("Delete").setIcon("trash").onClick(() => {
              void this.app.fileManager.trashFile(file).then(() => {
                this.requestRender();
              });
            });
          });
          menu.showAtMouseEvent(e);
        });
      }
      if (++sinceYield >= RENDER_YIELD_EVERY) {
        container.appendChild(fragment);
        await new Promise((r) => setTimeout(r, 0));
        sinceYield = 0;
      }
    }
    if (fragment.childNodes.length > 0)
      container.appendChild(fragment);
  }
  isImageFile(file) {
    return ["png", "jpg", "jpeg", "gif", "webp", "svg", "bmp", "avif"].includes(file.extension.toLowerCase());
  }
  /**
   * Cmd/Ctrl+クリックでキャンバス上の該当ノードへフォーカスする。
   * 同一ファイルの複数ノードは1件ずつサイクルし、canvasが閉じていれば開き直す。
   */
  async focusCanvasNode(file) {
    var _a;
    try {
      const canvasPath = this.canvasSourcePath;
      if (!canvasPath)
        return;
      const canvasFile = this.app.vault.getAbstractFileByPath(canvasPath);
      if (!(canvasFile instanceof import_obsidian.TFile)) {
        new import_obsidian.Notice(`Canvas not found: ${canvasPath}`);
        return;
      }
      const leaf = await this.ensureCanvasLeafOpen(canvasFile);
      if (!leaf) {
        new import_obsidian.Notice("Canvas\u3092\u958B\u3051\u307E\u305B\u3093\u3067\u3057\u305F");
        return;
      }
      const canvas = await this.waitForCanvasNodes(leaf);
      if (!canvas) {
        new import_obsidian.Notice("Canvas\u306E\u8AAD\u307F\u8FBC\u307F\u306B\u5931\u6557\u3057\u307E\u3057\u305F");
        return;
      }
      const matches = this.findCanvasNodesForFile(canvas, file);
      if (matches.length === 0) {
        new import_obsidian.Notice("Canvas\u4E0A\u306B\u898B\u3064\u304B\u308A\u307E\u305B\u3093\uFF08\u672A\u4FDD\u5B58\u306E\u53EF\u80FD\u6027\u304C\u3042\u308A\u307E\u3059\uFF09");
        return;
      }
      const prev = (_a = this.canvasFocusCycle[file.path]) != null ? _a : -1;
      const next = (prev + 1) % matches.length;
      this.canvasFocusCycle[file.path] = next;
      const node = matches[next];
      this.applyCanvasFocus(canvas, node);
    } catch (e) {
      console.error("Focus canvas node failed", e);
      new import_obsidian.Notice("Canvas\u3078\u306E\u30D5\u30A9\u30FC\u30AB\u30B9\u306B\u5931\u6557\u3057\u307E\u3057\u305F");
    }
  }
  applyCanvasFocus(canvas, node) {
    const c = canvas;
    const n = node;
    try {
      if (typeof c.deselectAll === "function")
        c.deselectAll();
      if (typeof c.selectOnly === "function")
        c.selectOnly(node);
      else if (typeof c.select === "function")
        c.select(node);
      if (typeof n.focus === "function") {
        try {
          n.focus();
        } catch (e) {
        }
      }
      if (typeof c.zoomToSelection === "function") {
        c.zoomToSelection();
      } else if (typeof c.zoomToBbox === "function") {
        if (typeof n.x === "number" && typeof n.y === "number") {
          const w = typeof n.width === "number" ? n.width : 400;
          const h = typeof n.height === "number" ? n.height : 300;
          c.zoomToBbox({ minX: n.x - w * 0.5, minY: n.y - h * 0.5, maxX: n.x + w * 1.5, maxY: n.y + h * 1.5 });
        }
      }
    } catch (e) {
      console.error("Focus canvas node failed", e);
      new import_obsidian.Notice("Canvas\u3078\u306E\u30D5\u30A9\u30FC\u30AB\u30B9\u306B\u5931\u6557\u3057\u307E\u3057\u305F");
    }
  }
  async ensureCanvasLeafOpen(canvasFile) {
    try {
      const leaves = this.app.workspace.getLeavesOfType("canvas");
      for (const leaf2 of leaves) {
        try {
          const f = leaf2.view.file;
          if ((f == null ? void 0 : f.path) === canvasFile.path) {
            await this.app.workspace.revealLeaf(leaf2);
            return leaf2;
          }
        } catch (e) {
        }
      }
      const leaf = this.app.workspace.getLeaf("tab");
      await leaf.openFile(canvasFile);
      await this.app.workspace.revealLeaf(leaf);
      return leaf;
    } catch (e) {
      return null;
    }
  }
  async waitForCanvasNodes(leaf, timeoutMs = 3e3) {
    const start = Date.now();
    while (Date.now() - start < timeoutMs) {
      try {
        const canvas = leaf.view.canvas;
        if ((canvas == null ? void 0 : canvas.nodes) && canvas.nodes.size > 0)
          return canvas;
      } catch (e) {
      }
      await new Promise((r) => window.setTimeout(r, 100));
    }
    try {
      const canvas = leaf.view.canvas;
      return canvas != null ? canvas : null;
    } catch (e) {
      return null;
    }
  }
  findCanvasNodesForFile(canvas, file) {
    var _a;
    const out = [];
    try {
      const nodes = canvas.nodes;
      if (!nodes || typeof nodes.values !== "function")
        return out;
      for (const n of nodes.values()) {
        const node = n;
        if (!node)
          continue;
        if (typeof node.url === "string" && node.url)
          continue;
        const fp = typeof node.filePath === "string" ? node.filePath : null;
        const nf = node.file;
        const resolved = nf instanceof import_obsidian.TFile ? nf.path : typeof nf === "string" ? nf : fp;
        if (resolved === file.path) {
          out.push(node);
          continue;
        }
        if (fp) {
          try {
            const dest = this.app.metadataCache.getFirstLinkpathDest(fp, (_a = this.canvasSourcePath) != null ? _a : "");
            if (dest instanceof import_obsidian.TFile && dest.path === file.path)
              out.push(node);
          } catch (e) {
          }
        }
      }
    } catch (e) {
    }
    return out;
  }
  getCanvasFiles() {
    return this.app.vault.getFiles().filter((f) => f.extension === "canvas");
  }
  generateCanvasNodeId() {
    try {
      const buf = new Uint8Array(8);
      crypto.getRandomValues(buf);
      return Array.from(buf).map((b) => b.toString(16).padStart(2, "0")).join("");
    } catch (e) {
      return Math.random().toString(36).slice(2, 10) + Math.random().toString(36).slice(2, 10);
    }
  }
  getCanvasNodeXY(node) {
    var _a;
    const pos = (_a = node.position) != null ? _a : void 0;
    const x = typeof node.x === "number" ? node.x : typeof (pos == null ? void 0 : pos.x) === "number" ? pos.x : 0;
    const y = typeof node.y === "number" ? node.y : typeof (pos == null ? void 0 : pos.y) === "number" ? pos.y : 0;
    const w = typeof node.width === "number" ? node.width : 400;
    const h = typeof node.height === "number" ? node.height : 300;
    return { x, y, w, h };
  }
  calcCanvasNewPosition(nodes) {
    if (!nodes || nodes.length === 0)
      return { x: 0, y: 0 };
    let maxRight = Number.NEGATIVE_INFINITY;
    let yForNew = 0;
    let hasValid = false;
    for (const n of nodes) {
      const { x, y, w } = this.getCanvasNodeXY(n);
      if (!Number.isFinite(x) || !Number.isFinite(y))
        continue;
      hasValid = true;
      const right = x + (Number.isFinite(w) ? w : 400);
      if (right > maxRight) {
        maxRight = right;
        yForNew = y;
      }
    }
    if (!hasValid)
      return { x: 0, y: 0 };
    const offset = nodes.length % 8 * 40;
    return { x: maxRight + 50, y: yForNew + offset };
  }
  getActiveCanvasFile() {
    try {
      const activeLeaf = this.app.workspace.activeLeaf;
      if (!activeLeaf)
        return null;
      const canvasLeaves = this.app.workspace.getLeavesOfType("canvas");
      if (!canvasLeaves.includes(activeLeaf))
        return null;
      const f = activeLeaf.view.file;
      if (f instanceof import_obsidian.TFile && f.extension === "canvas")
        return f;
    } catch (e) {
    }
    return null;
  }
  pickCanvasFile(files) {
    return new Promise((resolve) => {
      const modal = new CanvasPickerModal(this.app, files, (f) => resolve(f));
      modal.open();
    });
  }
  async sendFileToCanvas(file) {
    try {
      const canvasFiles = this.getCanvasFiles();
      if (canvasFiles.length === 0) {
        await this.createCanvasAndAdd(file);
        return;
      }
      const active = this.getActiveCanvasFile();
      if (active && canvasFiles.some((f) => f.path === active.path)) {
        await this.addFileToCanvas(active, file);
        return;
      }
      if (canvasFiles.length === 1) {
        await this.addFileToCanvas(canvasFiles[0], file);
        return;
      }
      const picked = await this.pickCanvasFile(canvasFiles);
      if (!picked)
        return;
      await this.addFileToCanvas(picked, file);
    } catch (e) {
      console.error("Send to Canvas failed", e);
      new import_obsidian.Notice("Canvas\u3078\u306E\u9001\u4FE1\u306B\u5931\u6557\u3057\u307E\u3057\u305F");
    }
  }
  async createCanvasAndAdd(file) {
    const baseName = "Untitled Canvas";
    const folder = this.selectedFolder ? `${this.selectedFolder}/` : "";
    let path = `${folder}${baseName}.canvas`;
    let counter = 1;
    while (this.app.vault.getAbstractFileByPath(path)) {
      path = `${folder}${baseName} ${counter}.canvas`;
      counter++;
    }
    const canvasFile = await this.app.vault.create(path, JSON.stringify({ nodes: [], edges: [] }, null, 2));
    await this.addFileToCanvas(canvasFile, file);
  }
  /** 送信先Canvasを開いていればそのタブをアクティブ化し、無ければ新規タブで開く */
  async revealCanvasFile(canvasFile) {
    try {
      const leaves = this.app.workspace.getLeavesOfType("canvas");
      for (const leaf2 of leaves) {
        try {
          const f = leaf2.view.file;
          if ((f == null ? void 0 : f.path) === canvasFile.path) {
            await this.app.workspace.revealLeaf(leaf2);
            return;
          }
        } catch (e) {
        }
      }
      const leaf = this.app.workspace.getLeaf("tab");
      await leaf.openFile(canvasFile);
    } catch (e) {
    }
  }
  async addFileToCanvas(canvasFile, file) {
    let raw = "";
    try {
      raw = await this.app.vault.read(canvasFile);
    } catch (e) {
      raw = "";
    }
    let data;
    try {
      data = raw && raw.trim().length >= 2 ? JSON.parse(raw) : { nodes: [], edges: [] };
    } catch (e) {
      data = { nodes: [], edges: [] };
    }
    if (!Array.isArray(data.nodes))
      data.nodes = [];
    if (!Array.isArray(data.edges))
      data.edges = [];
    const { x, y } = this.calcCanvasNewPosition(data.nodes);
    data.nodes.push({
      id: this.generateCanvasNodeId(),
      type: "file",
      file: file.path,
      x,
      y,
      width: 400,
      height: 300
    });
    await this.app.vault.modify(canvasFile, JSON.stringify(data, null, 2));
    new import_obsidian.Notice(`Sent ${file.basename} \u2192 ${canvasFile.basename}`);
    await this.revealCanvasFile(canvasFile);
  }
};
var KeepView = _KeepView;
/** アプリ全体で開いている編集モーダルの数。1以上なら背後の再描画を抑止する */
KeepView.openModalCount = 0;
/** 全canvas共有の使い回しスクラッチファイル名。canvas名を含めないことでリネーム時の増殖を防ぐ */
KeepView.SHARED_SCRATCH_NAME = "masonry-scratch.md";
/** 旧形式(canvas名ベース)の残骸掃除はセッション中1回だけ */
KeepView.legacyScratchCleaned = false;
var CanvasPickerModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, files, onPick) {
    super(app);
    this.picked = false;
    this.files = files;
    this.onPick = onPick;
    this.setPlaceholder("Send to Canvas: select target canvas");
  }
  getItems() {
    return this.files;
  }
  getItemText(file) {
    return file.path;
  }
  onChooseItem(file) {
    this.picked = true;
    this.onPick(file);
  }
  onClose() {
    super.onClose();
    const self = this;
    window.setTimeout(() => {
      if (!self.picked)
        self.onPick(null);
    }, 50);
  }
};
var KeepPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.canvasHeaderActions = /* @__PURE__ */ new Map();
    this.headerUpdateTimer = null;
    /**
     * Canvasカード左上のファイル名ラベル(.canvas-node-label)の素の左クリックを、
     * 右側の分割ペインで開く動作に変える。修飾キー付き・中クリックはコアに任せる。
     */
    this.onCanvasLabelClickCapture = (evt) => {
      var _a;
      if (!this.settings.canvasLabelSplitEnabled)
        return;
      if (evt.button !== 0)
        return;
      if (evt.metaKey || evt.ctrlKey || evt.shiftKey || evt.altKey)
        return;
      if (evt.defaultPrevented)
        return;
      const target = evt.target;
      if (!target || typeof target.closest !== "function")
        return;
      const labelEl = target.closest(".canvas-node-label");
      if (!labelEl)
        return;
      if (labelEl.closest(".canvas-node-group, .canvas-group-label, .canvas-path-label, .canvas-edge"))
        return;
      const canvasLeaf = this.app.workspace.getLeavesOfType("canvas").find((l) => {
        try {
          return l.view.containerEl.contains(target);
        } catch (e) {
          return false;
        }
      });
      if (!canvasLeaf)
        return;
      const view = canvasLeaf.view;
      const nodeEl = labelEl.closest(".canvas-node");
      let linktext = null;
      try {
        const nodes = (_a = view.canvas) == null ? void 0 : _a.nodes;
        if (nodes && typeof nodes.values === "function" && nodeEl) {
          for (const n of nodes.values()) {
            const node = n;
            if ((node == null ? void 0 : node.nodeEl) !== nodeEl)
              continue;
            if (typeof node.url === "string" && node.url)
              return;
            if (typeof node.filePath === "string" && node.filePath) {
              linktext = node.filePath + (typeof node.subpath === "string" ? node.subpath : "");
            }
            break;
          }
        }
      } catch (e) {
      }
      if (!linktext)
        return;
      const sourcePath = view.file instanceof import_obsidian.TFile ? view.file.path : "";
      const dest = this.app.metadataCache.getFirstLinkpathDest(linktext, sourcePath);
      if (!(dest instanceof import_obsidian.TFile))
        return;
      evt.preventDefault();
      evt.stopPropagation();
      void this.openInRightSplit(dest, canvasLeaf);
    };
  }
  async onload() {
    await this.loadSettings();
    this.registerView(KEEP_VIEW_TYPE, (leaf) => {
      var _a;
      const view = new KeepView(leaf);
      view.scratchFolder = this.settings.scratchFolder;
      view.newFileFolder = (_a = this.settings.newFileFolder) != null ? _a : "";
      return view;
    });
    this.addRibbonIcon("layout-grid", "Open note masonry", () => void this.activateView());
    this.addSettingTab(new NoteMasonrySettingTab(this.app, this));
    this.registerDomEvent(document, "click", this.onCanvasLabelClickCapture, true);
    this.registerEvent(this.app.workspace.on("active-leaf-change", () => this.scheduleCanvasHeaderUpdate()));
    this.registerEvent(this.app.workspace.on("layout-change", () => this.scheduleCanvasHeaderUpdate()));
    this.registerEvent(this.app.workspace.on("file-open", () => this.scheduleCanvasHeaderUpdate()));
    this.app.workspace.onLayoutReady(() => this.updateCanvasHeaderButtons());
    this.updateBodyClass();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    var _a;
    this.settings.scratchFolder = normalizeScratchFolder(this.settings.scratchFolder);
    this.settings.newFileFolder = normalizeNewFileFolder((_a = this.settings.newFileFolder) != null ? _a : "");
    await this.saveData(this.settings);
    this.updateBodyClass();
    this.syncSettingsToViews();
  }
  /** 設定変更を既存の全KeepViewへ反映する */
  syncSettingsToViews() {
    var _a;
    try {
      for (const leaf of this.app.workspace.getLeavesOfType(KEEP_VIEW_TYPE)) {
        const view = leaf.view;
        if (view instanceof KeepView) {
          view.scratchFolder = this.settings.scratchFolder;
          view.newFileFolder = (_a = this.settings.newFileFolder) != null ? _a : "";
        }
      }
    } catch (e) {
    }
  }
  updateBodyClass() {
    document.body.toggleClass("note-masonry-canvas-label-split", this.settings.canvasLabelSplitEnabled);
  }
  onunload() {
    document.body.removeClass("note-masonry-canvas-label-split");
    for (const el of this.canvasHeaderActions.values()) {
      try {
        el.remove();
      } catch (e) {
      }
    }
    this.canvasHeaderActions.clear();
    if (this.headerUpdateTimer !== null) {
      window.clearTimeout(this.headerUpdateTimer);
      this.headerUpdateTimer = null;
    }
  }
  scheduleCanvasHeaderUpdate() {
    if (this.headerUpdateTimer !== null) {
      window.clearTimeout(this.headerUpdateTimer);
    }
    this.headerUpdateTimer = window.setTimeout(() => {
      this.headerUpdateTimer = null;
      this.updateCanvasHeaderButtons();
    }, 150);
  }
  /**
   * canvasビューのview-header（3点メニュー左）にCard View絞り込みボタンを注入する。
   * header再描画で消えるため冪等な再付与＋不要分の除去を行う。
   */
  updateCanvasHeaderButtons() {
    try {
      const canvasLeaves = this.app.workspace.getLeavesOfType("canvas");
      const alive = new Set(canvasLeaves);
      for (const [leaf, el] of Array.from(this.canvasHeaderActions.entries())) {
        if (!alive.has(leaf)) {
          try {
            el.remove();
          } catch (e) {
          }
          this.canvasHeaderActions.delete(leaf);
          continue;
        }
        if (!el.isConnected) {
          this.canvasHeaderActions.delete(leaf);
        }
      }
      for (const leaf of canvasLeaves) {
        if (this.canvasHeaderActions.has(leaf))
          continue;
        try {
          const view = leaf.view;
          if (!view || typeof view.addAction !== "function")
            continue;
          const canvasFile = view.file;
          if (!(canvasFile instanceof import_obsidian.TFile) || canvasFile.extension !== "canvas")
            continue;
          const el = view.addAction("layout-grid", "\u3053\u306E\u30AD\u30E3\u30F3\u30D0\u30B9\u5185\u306E\u30D5\u30A1\u30A4\u30EB\u3092Card View\u3067\u8868\u793A", () => {
            const current = leaf.view.file;
            if (current instanceof import_obsidian.TFile && current.extension === "canvas") {
              void this.openCanvasFilteredView(current);
            }
          });
          el.addClass("note-masonry-canvas-filter-btn");
          el.setAttr("aria-label", "\u3053\u306E\u30AD\u30E3\u30F3\u30D0\u30B9\u5185\u306E\u30D5\u30A1\u30A4\u30EB\u3092Card View\u3067\u8868\u793A");
          this.canvasHeaderActions.set(leaf, el);
        } catch (e) {
        }
      }
    } catch (e) {
    }
  }
  /**
   * 既存の右側リーフがあれば再利用し、なければ右にvertical分割を作って開く。
   * 同一ファイルを既に開いているリーフがあればそこを優先してペイン増殖を防ぐ。
   * KeepView/canvas自体は再利用候補から除外する。
   */
  async openInRightSplit(file, canvasLeaf) {
    var _a;
    const ws = this.app.workspace;
    const leaves = [];
    ws.iterateRootLeaves((l) => leaves.push(l));
    const candidates = leaves.filter((l) => {
      var _a2, _b;
      try {
        const t = (_b = (_a2 = l.view).getViewType) == null ? void 0 : _b.call(_a2);
        return t !== KEEP_VIEW_TYPE && t !== "canvas";
      } catch (e) {
        return true;
      }
    });
    let target = null;
    if (candidates.length > 0) {
      try {
        const same = candidates.find((l) => {
          var _a2;
          try {
            return ((_a2 = l.view.file) == null ? void 0 : _a2.path) === file.path;
          } catch (e) {
            return false;
          }
        });
        if (same) {
          target = same;
        } else {
          target = (_a = candidates.find((l) => l !== canvasLeaf)) != null ? _a : null;
        }
      } catch (e) {
        target = null;
      }
    }
    if (!target) {
      target = ws.getLeaf("split", "vertical");
    }
    await target.openFile(file);
    await ws.revealLeaf(target);
  }
  /**
   * 指定canvasで絞り込んだCard Viewを右分割で開く。既存があれば再利用する。
   */
  async openCanvasFilteredView(canvasFile) {
    const ws = this.app.workspace;
    const keepLeaves = ws.getLeavesOfType(KEEP_VIEW_TYPE);
    for (const leaf2 of keepLeaves) {
      try {
        const v = leaf2.view;
        if (v instanceof KeepView && v.canvasSourcePath === canvasFile.path) {
          await ws.revealLeaf(leaf2);
          v.requestRender();
          return;
        }
      } catch (e) {
      }
    }
    const reusable = keepLeaves.find((leaf2) => {
      try {
        return leaf2.view.canvasSourcePath != null;
      } catch (e) {
        return false;
      }
    });
    if (reusable) {
      await reusable.setViewState({
        type: KEEP_VIEW_TYPE,
        active: true,
        state: { canvasSourcePath: canvasFile.path }
      });
      await ws.revealLeaf(reusable);
      return;
    }
    const leaf = ws.getLeaf("split", "vertical");
    await leaf.setViewState({
      type: KEEP_VIEW_TYPE,
      active: true,
      state: { canvasSourcePath: canvasFile.path }
    });
    await ws.revealLeaf(leaf);
  }
  async activateView() {
    const { workspace } = this.app;
    const leaf = workspace.getLeaf("tab");
    await leaf.setViewState({ type: KEEP_VIEW_TYPE, active: true });
    await workspace.revealLeaf(leaf);
  }
};
var NoteMasonrySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Open canvas label in right split").setDesc("Single-click a file name label on Canvas to open it in the right split (created if needed). Cmd/Ctrl+click behavior is unchanged.").addToggle((toggle) => toggle.setValue(this.plugin.settings.canvasLabelSplitEnabled).onChange(async (value) => {
      this.plugin.settings.canvasLabelSplitEnabled = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Default location for new files").setDesc("Default folder for files created with the + button in Card View (vault-relative, empty means vault root). When a folder filter is active, that folder takes precedence. Missing folders are created automatically.").addText((text) => {
      var _a;
      return text.setPlaceholder("e.g. Inbox (empty = vault root)").setValue((_a = this.plugin.settings.newFileFolder) != null ? _a : "").onChange(async (value) => {
        this.plugin.settings.newFileFolder = normalizeNewFileFolder(value);
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Scratch folder for text editing").setDesc("Location of the reusable file used to edit text cards inside a canvas in the large modal (vault-relative, one shared file for all canvases, never auto-deleted). To keep it out of search, we recommend adding it under Settings \u2192 Files and links \u2192 Excluded files.").addText((text) => text.setPlaceholder(DEFAULT_SCRATCH_FOLDER).setValue(this.plugin.settings.scratchFolder).onChange(async (value) => {
      this.plugin.settings.scratchFolder = normalizeScratchFolder(value);
      await this.plugin.saveSettings();
    }));
  }
};
