/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  KEEP_VIEW_TYPE: () => KEEP_VIEW_TYPE,
  KeepView: () => KeepView,
  default: () => KeepPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var KEEP_VIEW_TYPE = "keep-view";
var DEFAULT_TAG_FILTER = "#WIP";
var RANDOM_FILE_COUNT = 15;
var DEFAULT_SETTINGS = {
  canvasLabelSplitEnabled: true
};
var NoteEditModal = class {
  constructor(app, file, keepLeaf, onCloseCallback, selectedFolder = "", selectedTag = "") {
    this.editorLeaf = null;
    this.prevActiveEditor = null;
    this.hasSavedActiveEditor = false;
    this.pushedModalScope = false;
    this.isOpen = false;
    this.origSetActiveLeaf = null;
    this.origGetActiveViewOfType = null;
    this.origGetActiveFile = null;
    this.onModalFocusIn = () => {
      this.claimActiveEditor();
    };
    this.app = app;
    this.file = file;
    this.keepLeaf = keepLeaf;
    this.onCloseCallback = onCloseCallback;
    this.selectedFolder = selectedFolder;
    this.selectedTag = selectedTag;
    this.scope = new import_obsidian.Scope(this.app.scope);
    this.scope.register(null, "Escape", () => {
      this.close();
      return false;
    });
    this.containerEl = document.createElement("div");
    this.containerEl.addClass("modal-container", "mod-dim");
    this.bgEl = this.containerEl.createDiv({ cls: "modal-bg keep-modal-bg" });
    this.bgEl.addEventListener("click", () => this.close());
    this.modalEl = this.containerEl.createDiv({ cls: "modal keep-editor-modal" });
    this.contentEl = this.modalEl.createDiv({ cls: "modal-content keep-editor-modal-content" });
  }
  open() {
    if (this.isOpen)
      return;
    this.isOpen = true;
    document.body.appendChild(this.containerEl);
    this.app.keymap.pushScope(this.scope);
    this.pushedModalScope = true;
    void this.onOpen();
  }
  getEditorView() {
    var _a;
    const view = (_a = this.editorLeaf) == null ? void 0 : _a.view;
    return view != null ? view : null;
  }
  isEditorFocused() {
    const ae = document.activeElement;
    return !!ae && !!this.contentEl && this.contentEl.contains(ae);
  }
  /** デタッチleaf内のviewを activeEditor として振る舞わせる。view.scopeはpushしない(Escを横取りしてモーダルが閉じなくなるため)。ホットキーはmodal scope→app.scopeへのフォールスルーで届く。 */
  claimActiveEditor() {
    const view = this.getEditorView();
    if (!view)
      return;
    if (!this.hasSavedActiveEditor) {
      this.prevActiveEditor = this.app.workspace.activeEditor;
      this.hasSavedActiveEditor = true;
    }
    if (this.app.workspace.activeEditor !== view) {
      this.app.workspace.activeEditor = view;
    }
  }
  releaseActiveEditor() {
    const view = this.getEditorView();
    if (this.hasSavedActiveEditor) {
      if (!view || this.app.workspace.activeEditor === view) {
        this.app.workspace.activeEditor = this.prevActiveEditor;
      }
      this.prevActiveEditor = null;
      this.hasSavedActiveEditor = false;
    }
  }
  /**
   * Obsidianコアは activeEditor が MarkdownView 外にあるとクリアしたり、
   * getActiveViewOfType/getActiveFile が背後のleafを返すため、
   * モーダル表示中だけworkspaceの該当箇所をモーダル内に向ける。
   * 閉じる際に必ず元に戻す。
   */
  patchWorkspace() {
    const ws = this.app.workspace;
    if (!this.origSetActiveLeaf) {
      const orig = ws.setActiveLeaf.bind(ws);
      this.origSetActiveLeaf = orig;
      const self = this;
      ws.setActiveLeaf = function(leaf, ...args) {
        if (self.isOpen && self.isEditorFocused())
          return;
        return orig.apply(ws, [leaf, ...args]);
      };
    }
    if (!this.origGetActiveViewOfType) {
      const orig = ws.getActiveViewOfType.bind(ws);
      this.origGetActiveViewOfType = orig;
      const self = this;
      ws.getActiveViewOfType = function(type) {
        var _a;
        const v = (_a = self.editorLeaf) == null ? void 0 : _a.view;
        try {
          if (self.isOpen && v && v instanceof type)
            return v;
        } catch (e) {
        }
        return orig.apply(ws, [type]);
      };
    }
    if (!this.origGetActiveFile) {
      const orig = ws.getActiveFile.bind(ws);
      this.origGetActiveFile = orig;
      const self = this;
      ws.getActiveFile = function() {
        if (self.isOpen && self.file)
          return self.file;
        return orig.apply(ws);
      };
    }
  }
  unpatchWorkspace() {
    const ws = this.app.workspace;
    if (this.origSetActiveLeaf) {
      ws.setActiveLeaf = this.origSetActiveLeaf;
      this.origSetActiveLeaf = null;
    }
    if (this.origGetActiveViewOfType) {
      ws.getActiveViewOfType = this.origGetActiveViewOfType;
      this.origGetActiveViewOfType = null;
    }
    if (this.origGetActiveFile) {
      ws.getActiveFile = this.origGetActiveFile;
      this.origGetActiveFile = null;
    }
  }
  async onOpen() {
    this.contentEl.empty();
    let isNewFile = false;
    if (!this.file) {
      const basePath = this.selectedFolder ? `${this.selectedFolder}/` : "";
      let newPath = `${basePath}Untitled.md`;
      let counter = 1;
      while (this.app.vault.getAbstractFileByPath(newPath)) {
        newPath = `Untitled ${counter}.md`;
        counter++;
      }
      this.file = await this.app.vault.create(newPath, "");
      if (this.selectedTag) {
        await this.app.fileManager.processFrontMatter(this.file, (fm) => {
          if (!fm.tags) {
            fm.tags = [];
          } else if (typeof fm.tags === "string") {
            fm.tags = [fm.tags];
          }
          const cleanTag = this.selectedTag.replace(/^#/, "");
          if (!fm.tags.includes(cleanTag)) {
            fm.tags.push(cleanTag);
          }
        });
      }
      isNewFile = true;
    }
    const LeafConstructor = this.keepLeaf.constructor;
    this.editorLeaf = new LeafConstructor(this.app);
    const leafEl = this.editorLeaf.containerEl;
    this.contentEl.appendChild(leafEl);
    if (this.editorLeaf && this.file) {
      const leaf = this.editorLeaf;
      await leaf.openFile(this.file);
      if (!this.isOpen || this.editorLeaf !== leaf) {
        leaf.detach();
        return;
      }
      this.patchWorkspace();
      this.contentEl.addEventListener("focusin", this.onModalFocusIn);
      this.claimActiveEditor();
      if (isNewFile) {
        setTimeout(() => {
          const inlineTitle = this.contentEl.querySelector(".inline-title");
          if (inlineTitle) {
            inlineTitle.focus();
            const range = document.createRange();
            range.selectNodeContents(inlineTitle);
            const sel = window.getSelection();
            if (sel) {
              sel.removeAllRanges();
              sel.addRange(range);
            }
          } else {
            const headerTitle = this.contentEl.querySelector(".view-header-title");
            if (headerTitle) {
              headerTitle.click();
            }
          }
        }, 150);
      }
    }
  }
  close() {
    if (!this.isOpen)
      return;
    this.isOpen = false;
    this.contentEl.removeEventListener("focusin", this.onModalFocusIn);
    this.releaseActiveEditor();
    this.unpatchWorkspace();
    if (this.pushedModalScope) {
      try {
        this.app.keymap.popScope(this.scope);
      } catch (e) {
      }
      this.pushedModalScope = false;
    }
    if (this.editorLeaf) {
      this.editorLeaf.detach();
      this.editorLeaf = null;
    }
    this.containerEl.remove();
    this.contentEl.empty();
    this.app.workspace.setActiveLeaf(this.keepLeaf, { focus: true });
    this.onCloseCallback();
  }
};
var KeepView = class extends import_obsidian.ItemView {
  constructor(leaf) {
    super(leaf);
    this.isRendering = false;
    this.renderTimeout = null;
    this.hasAppliedDefaultTagFilter = false;
    this.selectedFolder = "";
    this.selectedTag = "";
    this.searchQuery = "";
    this.isRandomMode = false;
    this.randomFiles = [];
  }
  getViewType() {
    return KEEP_VIEW_TYPE;
  }
  getDisplayText() {
    return "Note masonry";
  }
  getIcon() {
    return "layout-grid";
  }
  getState() {
    return {
      ...super.getState(),
      selectedFolder: this.selectedFolder,
      selectedTag: this.selectedTag,
      searchQuery: this.searchQuery
    };
  }
  async setState(state, result) {
    if (typeof state.selectedFolder === "string") {
      this.selectedFolder = state.selectedFolder;
    }
    if (typeof state.selectedTag === "string") {
      this.selectedTag = state.selectedTag;
      this.hasAppliedDefaultTagFilter = true;
    }
    if (typeof state.searchQuery === "string") {
      this.searchQuery = state.searchQuery;
    }
    this.isRandomMode = false;
    this.randomFiles = [];
    await super.setState(state, result);
    this.requestRender();
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("keep-view-container");
    const filterContainer = container.createEl("div", { cls: "keep-filter-container" });
    const leftFilters = filterContainer.createEl("div", { cls: "keep-filter-left" });
    this.folderSelect = leftFilters.createEl("select", { cls: "keep-select" });
    this.folderSelect.addEventListener("change", (e) => {
      this.selectedFolder = e.target.value;
      this.adjustSelectWidth(this.folderSelect);
      this.exitRandomMode();
      this.requestRender();
    });
    this.tagSelect = leftFilters.createEl("select", { cls: "keep-select" });
    this.tagSelect.addEventListener("change", (e) => {
      this.selectedTag = e.target.value;
      this.adjustSelectWidth(this.tagSelect);
      this.exitRandomMode();
      this.requestRender();
    });
    this.randomButton = filterContainer.createEl("button", {
      cls: "keep-random-button",
      attr: { "aria-label": "Show 15 random notes", "title": "\u30E9\u30F3\u30C0\u30E0\u306B15\u4EF6\u8868\u793A" }
    });
    (0, import_obsidian.setIcon)(this.randomButton, "shuffle");
    this.randomButton.addEventListener("click", () => {
      this.showRandomFiles();
    });
    const searchContainer = filterContainer.createEl("div", { cls: "keep-search-container" });
    const searchWrapper = searchContainer.createEl("div", { cls: "keep-search-wrapper" });
    const searchIconWrapper = searchWrapper.createEl("div", { cls: "keep-search-icon" });
    (0, import_obsidian.setIcon)(searchIconWrapper, "search");
    this.searchInput = searchWrapper.createEl("input", {
      cls: "keep-search-input",
      attr: {
        type: "text",
        placeholder: "Search notes..."
      }
    });
    this.searchInput.value = this.searchQuery;
    this.searchInput.addEventListener("input", (e) => {
      this.searchQuery = e.target.value;
      this.updateSearchVisibility();
      this.exitRandomMode();
      this.requestRender();
    });
    this.searchInput.addEventListener("focus", () => {
      searchWrapper.addClass("is-focused");
    });
    this.searchInput.addEventListener("blur", () => {
      searchWrapper.removeClass("is-focused");
    });
    this.updateSearchVisibility();
    const createButton = filterContainer.createEl("button", {
      cls: "keep-create-button"
    });
    (0, import_obsidian.setIcon)(createButton, "plus");
    createButton.addEventListener("click", () => {
      new NoteEditModal(this.app, null, this.leaf, () => this.requestRender(), this.selectedFolder, this.selectedTag).open();
    });
    this.gridContainer = container.createEl("div", { cls: "keep-grid-wrapper" });
    this.registerEvent(this.app.vault.on("create", () => this.requestRender()));
    this.registerEvent(this.app.vault.on("modify", () => this.requestRender()));
    this.registerEvent(this.app.vault.on("delete", () => this.requestRender()));
    this.registerEvent(this.app.vault.on("rename", () => this.requestRender()));
    this.registerEvent(this.app.metadataCache.on("changed", () => this.requestRender()));
    await this.renderGrid();
  }
  updateSearchVisibility() {
    const searchWrapper = this.containerEl.querySelector(".keep-search-wrapper");
    if (searchWrapper) {
      if (this.searchQuery) {
        searchWrapper.addClass("has-value");
      } else {
        searchWrapper.removeClass("has-value");
      }
    }
  }
  requestRender() {
    if (this.renderTimeout) {
      clearTimeout(this.renderTimeout);
    }
    this.renderTimeout = setTimeout(() => {
      void this.renderGrid();
    }, 300);
  }
  applyDefaultTagFilter() {
    var _a;
    if (this.hasAppliedDefaultTagFilter)
      return;
    if (this.selectedTag) {
      this.hasAppliedDefaultTagFilter = true;
      return;
    }
    const tags = Object.keys((_a = this.app.metadataCache.getTags()) != null ? _a : {}).sort();
    if (tags.length === 0)
      return;
    if (tags.includes(DEFAULT_TAG_FILTER)) {
      this.selectedTag = DEFAULT_TAG_FILTER;
    } else {
      this.selectedTag = tags[0];
    }
    this.hasAppliedDefaultTagFilter = true;
  }
  showRandomFiles() {
    const all = this.app.vault.getMarkdownFiles();
    for (let i = all.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [all[i], all[j]] = [all[j], all[i]];
    }
    this.randomFiles = all.slice(0, RANDOM_FILE_COUNT);
    this.isRandomMode = true;
    this.updateRandomButtonState();
    this.requestRender();
  }
  exitRandomMode() {
    if (!this.isRandomMode)
      return;
    this.isRandomMode = false;
    this.randomFiles = [];
    this.updateRandomButtonState();
  }
  updateRandomButtonState() {
    if (this.randomButton) {
      this.randomButton.toggleClass("is-active", this.isRandomMode);
    }
  }
  updateFilterUI() {
    const folders = this.app.vault.getAllLoadedFiles().filter((f) => f instanceof import_obsidian.TFolder);
    const tags = Object.keys(this.app.metadataCache.getTags()).sort();
    if (this.folderSelect.options.length !== folders.length + 1) {
      const currentFolder = this.selectedFolder;
      this.folderSelect.empty();
      this.folderSelect.createEl("option", { value: "", text: "All folders" });
      folders.forEach((f) => {
        if (f.path === "/")
          return;
        const option = this.folderSelect.createEl("option", { value: f.path, text: f.path });
        if (f.path === currentFolder)
          option.selected = true;
      });
    }
    if (this.tagSelect.options.length !== tags.length + 1) {
      const currentTag = this.selectedTag;
      this.tagSelect.empty();
      this.tagSelect.createEl("option", { value: "", text: "All tags" });
      tags.forEach((t) => {
        const option = this.tagSelect.createEl("option", { value: t, text: t });
        if (t === currentTag)
          option.selected = true;
      });
    }
    this.folderSelect.value = this.selectedFolder;
    this.adjustSelectWidth(this.folderSelect);
    this.tagSelect.value = this.selectedTag;
    this.adjustSelectWidth(this.tagSelect);
  }
  adjustSelectWidth(select) {
    if (!select || select.options.length === 0)
      return;
    const tempSpan = document.createElement("span");
    tempSpan.setCssProps({
      "visibility": "hidden",
      "position": "absolute",
      "white-space": "nowrap"
    });
    const computedStyle = window.getComputedStyle(select);
    tempSpan.setCssProps({
      "font-size": computedStyle.fontSize,
      "font-family": computedStyle.fontFamily
    });
    tempSpan.innerText = select.options[select.selectedIndex].text;
    document.body.appendChild(tempSpan);
    const textWidth = tempSpan.getBoundingClientRect().width;
    document.body.removeChild(tempSpan);
    select.style.width = `${textWidth + 20}px`;
  }
  async renderGrid() {
    var _a;
    if (this.isRendering)
      return;
    this.isRendering = true;
    try {
      this.applyDefaultTagFilter();
      this.updateFilterUI();
      this.updateRandomButtonState();
      let files;
      if (this.isRandomMode) {
        const existingPaths = new Set(this.app.vault.getMarkdownFiles().map((f) => f.path));
        files = this.randomFiles.filter((f) => existingPaths.has(f.path));
      } else {
        let filtered = this.app.vault.getMarkdownFiles();
        if (this.selectedFolder) {
          filtered = filtered.filter((f) => {
            var _a2, _b;
            return ((_a2 = f.parent) == null ? void 0 : _a2.path) === this.selectedFolder || ((_b = f.parent) == null ? void 0 : _b.path.startsWith(this.selectedFolder + "/"));
          });
        }
        if (this.selectedTag) {
          filtered = filtered.filter((f) => {
            const cache = this.app.metadataCache.getFileCache(f);
            const tags = cache ? (0, import_obsidian.getAllTags)(cache) || [] : [];
            return tags.includes(this.selectedTag);
          });
        }
        if (this.searchQuery) {
          const query = this.searchQuery.toLowerCase();
          const searchPromises = filtered.map(async (f) => {
            const content = await this.app.vault.cachedRead(f);
            const cache = this.app.metadataCache.getFileCache(f);
            if (f.basename.toLowerCase().includes(query)) {
              return true;
            }
            let contentWithoutFrontmatter = content;
            if (cache == null ? void 0 : cache.frontmatterPosition) {
              contentWithoutFrontmatter = content.substring(cache.frontmatterPosition.end.offset);
            } else {
              contentWithoutFrontmatter = content.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n/, "");
            }
            return contentWithoutFrontmatter.toLowerCase().includes(query);
          });
          const searchResults = await Promise.all(searchPromises);
          filtered = filtered.filter((_, index) => searchResults[index]);
        }
        files = filtered;
      }
      files.sort((a, b) => b.stat.mtime - a.stat.mtime);
      const pinnedFiles = [];
      const unpinnedFiles = [];
      for (const file of files) {
        const cache = this.app.metadataCache.getFileCache(file);
        const isPinned = ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.pinned) === true;
        if (isPinned)
          pinnedFiles.push(file);
        else
          unpinnedFiles.push(file);
      }
      this.gridContainer.empty();
      if (pinnedFiles.length > 0) {
        this.gridContainer.createEl("h3", { text: "Pinned", cls: "keep-section-title" });
        const pinnedGrid = this.gridContainer.createEl("div", { cls: "keep-grid" });
        await this.renderCards(pinnedFiles, pinnedGrid);
        if (unpinnedFiles.length > 0) {
          this.gridContainer.createEl("h3", { text: "Others", cls: "keep-section-title keep-section-title-others" });
        }
      }
      const unpinnedGrid = this.gridContainer.createEl("div", { cls: "keep-grid" });
      await this.renderCards(unpinnedFiles, unpinnedGrid);
    } finally {
      this.isRendering = false;
    }
  }
  async renderCards(files, container) {
    var _a;
    const fragment = document.createDocumentFragment();
    for (const file of files) {
      const content = await this.app.vault.cachedRead(file);
      const cache = this.app.metadataCache.getFileCache(file);
      let contentWithoutFrontmatter = content;
      if (cache == null ? void 0 : cache.frontmatterPosition) {
        contentWithoutFrontmatter = content.substring(cache.frontmatterPosition.end.offset).trim();
      } else {
        contentWithoutFrontmatter = content.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n/, "").trim();
      }
      const imageRegex = /!\[.*?\]\((.*?)\)|!\[\[(.*?)\]\]/g;
      const images = [];
      let match;
      while ((match = imageRegex.exec(contentWithoutFrontmatter)) !== null && images.length < 2) {
        const url = match[1] || match[2];
        if (url) {
          images.push(url);
        }
      }
      const resolvedImages = images.map((img) => {
        if (img.startsWith("http://") || img.startsWith("https://") || img.startsWith("app://") || img.startsWith("data:")) {
          return img;
        }
        const linkedFile = this.app.metadataCache.getFirstLinkpathDest(img, file.path);
        if (linkedFile) {
          return this.app.vault.getResourcePath(linkedFile);
        }
        return null;
      }).filter((img) => img !== null);
      const snippetText = contentWithoutFrontmatter.replace(/!\[.*?\]\(.*?\)|!\[\[.*?\]\]/g, "").trim();
      const snippet = snippetText.substring(0, 250) + (snippetText.length > 250 ? "..." : "");
      const card = fragment.createEl("div", { cls: "keep-card" });
      card.draggable = true;
      let cardWasDragged = false;
      card.addEventListener("dragstart", (e) => {
        cardWasDragged = true;
        card.addClass("is-dragging");
        try {
          const dm = this.app.dragManager;
          if ((dm == null ? void 0 : dm.dragFile) && (dm == null ? void 0 : dm.onDragStart)) {
            const info = dm.dragFile(e, file);
            if (info)
              dm.onDragStart(e, info);
          } else if (dm == null ? void 0 : dm.dragFile) {
            dm.dragFile(e, file);
          } else if (e.dataTransfer) {
            e.dataTransfer.effectAllowed = "copy";
            try {
              e.dataTransfer.setData("text/plain", file.path);
            } catch (e2) {
            }
          }
        } catch (e2) {
        }
      });
      card.addEventListener("dragend", () => {
        card.removeClass("is-dragging");
        window.setTimeout(() => {
          cardWasDragged = false;
        }, 150);
      });
      if (resolvedImages.length > 0) {
        const imgContainer = card.createEl("div", { cls: `keep-card-images keep-card-images-${resolvedImages.length}` });
        resolvedImages.forEach((img) => {
          const imgEl = imgContainer.createEl("img", { attr: { src: img } });
          imgEl.draggable = false;
        });
      }
      const splitBtn = card.createEl("button", {
        cls: "keep-split-btn",
        attr: { "aria-label": "Open in split view" }
      });
      (0, import_obsidian.setIcon)(splitBtn, "panel-right");
      const splitSvg = splitBtn.querySelector("svg");
      if (splitSvg) {
        splitSvg.setAttribute("fill", "none");
        splitSvg.setAttribute("stroke", "currentColor");
      }
      splitBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        const leaf = this.app.workspace.getLeaf("split");
        void leaf.openFile(file);
      });
      const pinBtn = card.createEl("button", { cls: "keep-pin-btn" });
      (0, import_obsidian.setIcon)(pinBtn, "pin");
      const svg = pinBtn.querySelector("svg");
      if (svg) {
        svg.setAttribute("fill", "none");
        svg.setAttribute("stroke", "currentColor");
      }
      const isPinned = ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.pinned) === true;
      if (isPinned) {
        pinBtn.addClass("is-pinned");
        if (svg) {
          svg.setAttribute("fill", "currentColor");
        }
      }
      pinBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        void this.app.fileManager.processFrontMatter(file, (fm) => {
          fm.pinned = !isPinned;
        });
      });
      const menuBtn = card.createEl("button", {
        cls: "keep-menu-btn",
        attr: { "aria-label": "Card menu" }
      });
      (0, import_obsidian.setIcon)(menuBtn, "more-horizontal");
      const menuSvg = menuBtn.querySelector("svg");
      if (menuSvg) {
        menuSvg.setAttribute("fill", "none");
        menuSvg.setAttribute("stroke", "currentColor");
      }
      menuBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        const menu = new import_obsidian.Menu();
        menu.addItem((item) => {
          item.setTitle("Delete").setIcon("trash").onClick(() => {
            void this.app.fileManager.trashFile(file).then(() => {
              this.requestRender();
            });
          });
        });
        menu.showAtMouseEvent(e);
      });
      const canvasBtn = card.createEl("button", {
        cls: "keep-canvas-btn",
        attr: { "aria-label": "Send to Canvas" }
      });
      (0, import_obsidian.setIcon)(canvasBtn, "layout-dashboard");
      const canvasSvg = canvasBtn.querySelector("svg");
      if (canvasSvg) {
        canvasSvg.setAttribute("fill", "none");
        canvasSvg.setAttribute("stroke", "currentColor");
      }
      canvasBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        void this.sendFileToCanvas(file);
      });
      if (file.basename) {
        card.createEl("h3", { text: file.basename, cls: "keep-card-title" });
      }
      if (snippet) {
        card.createEl("div", { text: snippet, cls: "keep-card-snippet" });
      }
      card.addEventListener("click", () => {
        if (cardWasDragged) {
          cardWasDragged = false;
          return;
        }
        new NoteEditModal(this.app, file, this.leaf, () => this.requestRender()).open();
      });
      card.addEventListener("contextmenu", (e) => {
        e.preventDefault();
        e.stopPropagation();
        const menu = new import_obsidian.Menu();
        menu.addItem((item) => {
          item.setTitle("Send to Canvas").setIcon("layout-dashboard").onClick(() => void this.sendFileToCanvas(file));
        });
        menu.addItem((item) => {
          item.setTitle("Send to new Canvas").setIcon("plus").onClick(() => void this.createCanvasAndAdd(file));
        });
        menu.addSeparator();
        menu.addItem((item) => {
          item.setTitle("Delete").setIcon("trash").onClick(() => {
            void this.app.fileManager.trashFile(file).then(() => {
              this.requestRender();
            });
          });
        });
        menu.showAtMouseEvent(e);
      });
    }
    container.appendChild(fragment);
  }
  getCanvasFiles() {
    return this.app.vault.getFiles().filter((f) => f.extension === "canvas");
  }
  generateCanvasNodeId() {
    try {
      const buf = new Uint8Array(8);
      crypto.getRandomValues(buf);
      return Array.from(buf).map((b) => b.toString(16).padStart(2, "0")).join("");
    } catch (e) {
      return Math.random().toString(36).slice(2, 10) + Math.random().toString(36).slice(2, 10);
    }
  }
  getCanvasNodeXY(node) {
    var _a;
    const pos = (_a = node.position) != null ? _a : void 0;
    const x = typeof node.x === "number" ? node.x : typeof (pos == null ? void 0 : pos.x) === "number" ? pos.x : 0;
    const y = typeof node.y === "number" ? node.y : typeof (pos == null ? void 0 : pos.y) === "number" ? pos.y : 0;
    const w = typeof node.width === "number" ? node.width : 400;
    const h = typeof node.height === "number" ? node.height : 300;
    return { x, y, w, h };
  }
  calcCanvasNewPosition(nodes) {
    if (!nodes || nodes.length === 0)
      return { x: 0, y: 0 };
    let maxRight = Number.NEGATIVE_INFINITY;
    let yForNew = 0;
    let hasValid = false;
    for (const n of nodes) {
      const { x, y, w } = this.getCanvasNodeXY(n);
      if (!Number.isFinite(x) || !Number.isFinite(y))
        continue;
      hasValid = true;
      const right = x + (Number.isFinite(w) ? w : 400);
      if (right > maxRight) {
        maxRight = right;
        yForNew = y;
      }
    }
    if (!hasValid)
      return { x: 0, y: 0 };
    const offset = nodes.length % 8 * 40;
    return { x: maxRight + 50, y: yForNew + offset };
  }
  getActiveCanvasFile() {
    try {
      const activeLeaf = this.app.workspace.activeLeaf;
      if (!activeLeaf)
        return null;
      const canvasLeaves = this.app.workspace.getLeavesOfType("canvas");
      if (!canvasLeaves.includes(activeLeaf))
        return null;
      const f = activeLeaf.view.file;
      if (f instanceof import_obsidian.TFile && f.extension === "canvas")
        return f;
    } catch (e) {
    }
    return null;
  }
  pickCanvasFile(files) {
    return new Promise((resolve) => {
      const modal = new CanvasPickerModal(this.app, files, (f) => resolve(f));
      modal.open();
    });
  }
  async sendFileToCanvas(file) {
    try {
      const canvasFiles = this.getCanvasFiles();
      if (canvasFiles.length === 0) {
        await this.createCanvasAndAdd(file);
        return;
      }
      const active = this.getActiveCanvasFile();
      if (active && canvasFiles.some((f) => f.path === active.path)) {
        await this.addFileToCanvas(active, file);
        return;
      }
      if (canvasFiles.length === 1) {
        await this.addFileToCanvas(canvasFiles[0], file);
        return;
      }
      const picked = await this.pickCanvasFile(canvasFiles);
      if (!picked)
        return;
      await this.addFileToCanvas(picked, file);
    } catch (e) {
      console.error("Send to Canvas failed", e);
      new import_obsidian.Notice("Canvas\u3078\u306E\u9001\u4FE1\u306B\u5931\u6557\u3057\u307E\u3057\u305F");
    }
  }
  async createCanvasAndAdd(file) {
    const baseName = "Untitled Canvas";
    const folder = this.selectedFolder ? `${this.selectedFolder}/` : "";
    let path = `${folder}${baseName}.canvas`;
    let counter = 1;
    while (this.app.vault.getAbstractFileByPath(path)) {
      path = `${folder}${baseName} ${counter}.canvas`;
      counter++;
    }
    const canvasFile = await this.app.vault.create(path, JSON.stringify({ nodes: [], edges: [] }, null, 2));
    await this.addFileToCanvas(canvasFile, file);
  }
  /** 送信先Canvasを開いていればそのタブをアクティブ化し、無ければ新規タブで開く */
  async revealCanvasFile(canvasFile) {
    try {
      const leaves = this.app.workspace.getLeavesOfType("canvas");
      for (const leaf2 of leaves) {
        try {
          const f = leaf2.view.file;
          if ((f == null ? void 0 : f.path) === canvasFile.path) {
            await this.app.workspace.revealLeaf(leaf2);
            return;
          }
        } catch (e) {
        }
      }
      const leaf = this.app.workspace.getLeaf("tab");
      await leaf.openFile(canvasFile);
    } catch (e) {
    }
  }
  async addFileToCanvas(canvasFile, file) {
    let raw = "";
    try {
      raw = await this.app.vault.read(canvasFile);
    } catch (e) {
      raw = "";
    }
    let data;
    try {
      data = raw && raw.trim().length >= 2 ? JSON.parse(raw) : { nodes: [], edges: [] };
    } catch (e) {
      data = { nodes: [], edges: [] };
    }
    if (!Array.isArray(data.nodes))
      data.nodes = [];
    if (!Array.isArray(data.edges))
      data.edges = [];
    const { x, y } = this.calcCanvasNewPosition(data.nodes);
    data.nodes.push({
      id: this.generateCanvasNodeId(),
      type: "file",
      file: file.path,
      x,
      y,
      width: 400,
      height: 300
    });
    await this.app.vault.modify(canvasFile, JSON.stringify(data, null, 2));
    new import_obsidian.Notice(`Sent ${file.basename} \u2192 ${canvasFile.basename}`);
    await this.revealCanvasFile(canvasFile);
  }
};
var CanvasPickerModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, files, onPick) {
    super(app);
    this.picked = false;
    this.files = files;
    this.onPick = onPick;
    this.setPlaceholder("Send to Canvas: select target canvas");
  }
  getItems() {
    return this.files;
  }
  getItemText(file) {
    return file.path;
  }
  onChooseItem(file) {
    this.picked = true;
    this.onPick(file);
  }
  onClose() {
    super.onClose();
    const self = this;
    window.setTimeout(() => {
      if (!self.picked)
        self.onPick(null);
    }, 50);
  }
};
var KeepPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    /**
     * Canvasカード左上のファイル名ラベル(.canvas-node-label)の素の左クリックを、
     * 右側の分割ペインで開く動作に変える。修飾キー付き・中クリックはコアに任せる。
     */
    this.onCanvasLabelClickCapture = (evt) => {
      var _a;
      if (!this.settings.canvasLabelSplitEnabled)
        return;
      if (evt.button !== 0)
        return;
      if (evt.metaKey || evt.ctrlKey || evt.shiftKey || evt.altKey)
        return;
      if (evt.defaultPrevented)
        return;
      const target = evt.target;
      if (!target || typeof target.closest !== "function")
        return;
      const labelEl = target.closest(".canvas-node-label");
      if (!labelEl)
        return;
      if (labelEl.closest(".canvas-node-group, .canvas-group-label, .canvas-path-label, .canvas-edge"))
        return;
      const canvasLeaf = this.app.workspace.getLeavesOfType("canvas").find((l) => {
        try {
          return l.view.containerEl.contains(target);
        } catch (e) {
          return false;
        }
      });
      if (!canvasLeaf)
        return;
      const view = canvasLeaf.view;
      const nodeEl = labelEl.closest(".canvas-node");
      let linktext = null;
      try {
        const nodes = (_a = view.canvas) == null ? void 0 : _a.nodes;
        if (nodes && typeof nodes.values === "function" && nodeEl) {
          for (const n of nodes.values()) {
            const node = n;
            if ((node == null ? void 0 : node.nodeEl) !== nodeEl)
              continue;
            if (typeof node.url === "string" && node.url)
              return;
            if (typeof node.filePath === "string" && node.filePath) {
              linktext = node.filePath + (typeof node.subpath === "string" ? node.subpath : "");
            }
            break;
          }
        }
      } catch (e) {
      }
      if (!linktext)
        return;
      const sourcePath = view.file instanceof import_obsidian.TFile ? view.file.path : "";
      const dest = this.app.metadataCache.getFirstLinkpathDest(linktext, sourcePath);
      if (!(dest instanceof import_obsidian.TFile))
        return;
      evt.preventDefault();
      evt.stopPropagation();
      void this.openInRightSplit(dest, canvasLeaf);
    };
  }
  async onload() {
    await this.loadSettings();
    this.registerView(KEEP_VIEW_TYPE, (leaf) => new KeepView(leaf));
    this.addRibbonIcon("layout-grid", "Open note masonry", () => void this.activateView());
    this.addSettingTab(new NoteMasonrySettingTab(this.app, this));
    this.registerDomEvent(document, "click", this.onCanvasLabelClickCapture, true);
    this.updateBodyClass();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.updateBodyClass();
  }
  updateBodyClass() {
    document.body.toggleClass("note-masonry-canvas-label-split", this.settings.canvasLabelSplitEnabled);
  }
  onunload() {
    document.body.removeClass("note-masonry-canvas-label-split");
  }
  /**
   * 既存の右側リーフがあれば再利用し、なければ右にvertical分割を作って開く。
   * 同一ファイルを既に開いているリーフがあればそこを優先してペイン増殖を防ぐ。
   */
  async openInRightSplit(file, canvasLeaf) {
    var _a;
    const ws = this.app.workspace;
    const leaves = [];
    ws.iterateRootLeaves((l) => leaves.push(l));
    let target = null;
    if (leaves.length > 1) {
      try {
        const same = leaves.find((l) => {
          var _a2;
          try {
            return ((_a2 = l.view.file) == null ? void 0 : _a2.path) === file.path;
          } catch (e) {
            return false;
          }
        });
        if (same) {
          target = same;
        } else {
          target = (_a = leaves.find((l) => l !== canvasLeaf)) != null ? _a : null;
        }
      } catch (e) {
        target = null;
      }
    }
    if (!target) {
      target = ws.getLeaf("split", "vertical");
    }
    await target.openFile(file);
    await ws.revealLeaf(target);
  }
  async activateView() {
    const { workspace } = this.app;
    const leaf = workspace.getLeaf("tab");
    await leaf.setViewState({ type: KEEP_VIEW_TYPE, active: true });
    await workspace.revealLeaf(leaf);
  }
};
var NoteMasonrySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Canvas\u30E9\u30D9\u30EB\u30AF\u30EA\u30C3\u30AF\u3067\u53F3\u306B\u958B\u304F").setDesc("Canvas\u306E\u30D5\u30A1\u30A4\u30EB\u540D\u30E9\u30D9\u30EB\u3092\u5358\u7D14\u30AF\u30EA\u30C3\u30AF\u3067\u53F3\u306E\u5206\u5272\u30DA\u30A4\u30F3\u306B\u958B\u304D\u307E\u3059(\u306A\u3051\u308C\u3070\u4F5C\u6210)\u3002Cmd/Ctrl+\u30AF\u30EA\u30C3\u30AF\u306E\u65E2\u5B9A\u52D5\u4F5C\u306F\u7DAD\u6301\u3055\u308C\u307E\u3059\u3002").addToggle((toggle) => toggle.setValue(this.plugin.settings.canvasLabelSplitEnabled).onChange(async (value) => {
      this.plugin.settings.canvasLabelSplitEnabled = value;
      await this.plugin.saveSettings();
    }));
  }
};
